import type { SupabaseClient } from "@supabase/supabase-js";
import type { RepositorySet } from "./contracts";
import type { CatalogState, ProductInput } from "@/lib/catalog-types";
import type { CommerceState } from "@/lib/commerce-types";
const cents=(value:number)=>Math.round(value*100);
const check=(error:{code?:string;message:string}|null)=>{if(!error)return;if(error.code==="23505")throw new Error("Já existe um registro com estes dados nesta empresa.");throw new Error(error.message)};
const statusFor=(i:ProductInput)=>i.status==="inactive"?"inactive" as const:(i.trackStock&&i.currentStock===0?"out_of_stock" as const:"available" as const);
export function createSupabaseRepositories(client:SupabaseClient,companyId:string):RepositorySet{
 const loadCatalog=async():Promise<CatalogState>=>{const[{data:categories,error:ce},{data:products,error:pe},{data:options,error:oe},{data:movements,error:me}]=await Promise.all([client.from("categories").select("*").eq("company_id",companyId).is("deleted_at",null),client.from("products").select("*").eq("company_id",companyId).is("deleted_at",null),client.from("product_options").select("*").eq("company_id",companyId).is("deleted_at",null),client.from("stock_movements").select("*").eq("company_id",companyId).order("created_at",{ascending:false})]);check(ce||pe||oe||me);return{version:1,company:{id:companyId,name:"Empresa"},categories:(categories??[]).map(r=>({id:r.id,companyId:r.company_id,name:r.name,description:r.description,status:r.status,displayOrder:r.display_order,createdAt:r.created_at,updatedAt:r.updated_at})),products:(products??[]).map(r=>({id:r.id,companyId:r.company_id,categoryId:r.category_id,name:r.name,description:r.description,price:r.price_cents/100,promotionalPrice:r.promotional_price_cents==null?undefined:r.promotional_price_cents/100,imageUrl:r.image_url,sku:r.sku,trackStock:r.track_stock,currentStock:r.current_stock,minimumStock:r.minimum_stock,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at})),productOptions:(options??[]).map(r=>({id:r.id,companyId:r.company_id,productId:r.product_id,name:r.name,price:r.price_cents/100,status:r.status,displayOrder:r.display_order})),movements:(movements??[]).map(r=>({id:r.id,companyId:r.company_id,productId:r.product_id,type:r.type,quantity:r.quantity,previousStock:r.previous_stock,resultingStock:r.resulting_stock,reason:r.reason,createdAt:r.created_at}))}};
 const loadCommerce=async():Promise<CommerceState>=>{const[{data:customers,error:ce},{data:orders,error:oe}]=await Promise.all([client.from("customers").select("*").eq("company_id",companyId).is("deleted_at",null),client.from("orders").select("*,order_items(*)").eq("company_id",companyId).is("deleted_at",null).order("created_at",{ascending:false})]);check(ce||oe);return{version:1,companyId,nextOrderNumber:Math.max(1,...(orders??[]).map(o=>Number(o.number)+1)),customers:(customers??[]).map(c=>({id:c.id,companyId:c.company_id,name:c.name,phone:c.phone,email:c.email,taxId:c.tax_id,address:c.address,notes:c.notes,status:c.status,createdAt:c.created_at,updatedAt:c.updated_at})),orders:(orders??[]).map(o=>({id:o.id,companyId:o.company_id,number:Number(o.number),customerId:o.customer_id,customerName:o.customer_name,customerPhone:o.customer_phone,createdAt:o.created_at,updatedAt:o.updated_at,items:(o.order_items??[]).map((i:Record<string,unknown>)=>({id:i.id as string,productId:i.product_id as string,productName:i.product_name as string,unitPrice:(i.unit_price_cents as number)/100,quantity:i.quantity as number,additions:i.additions as string[],note:i.note as string|undefined,total:(i.total_cents as number)/100})),fulfillment:o.fulfillment,deliveryAddress:o.delivery_address,subtotal:o.subtotal_cents/100,discount:o.discount_cents/100,deliveryFee:o.delivery_fee_cents/100,total:o.total_cents/100,paymentMethod:o.payment_method,paymentStatus:o.payment_status,status:o.status,stockApplied:o.stock_applied,cancellationReason:o.cancellation_reason}))}};
 return{mode:"supabase",catalog:{
  load:loadCatalog,
  createCategory:async(i)=>{const{error}=await client.from("categories").insert({company_id:companyId,name:i.name,description:i.description,status:i.status,display_order:i.displayOrder});check(error);return loadCatalog()},
  updateCategory:async(id,i)=>{const{error}=await client.from("categories").update({name:i.name,description:i.description,status:i.status,display_order:i.displayOrder}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()},
  deleteCategory:async(id)=>{const{count,error:ce}=await client.from("products").select("id",{count:"exact",head:true}).eq("company_id",companyId).eq("category_id",id).is("deleted_at",null);check(ce);if((count??0)>0)throw new Error("Mova os produtos desta categoria antes de excluí-la.");const{error}=await client.from("categories").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()},
  createProduct:async(i)=>{const{error}=await client.from("products").insert({company_id:companyId,category_id:i.categoryId,name:i.name,description:i.description,price_cents:cents(i.price),promotional_price_cents:i.promotionalPrice==null?null:cents(i.promotionalPrice),image_url:i.imageUrl,sku:i.sku,track_stock:i.trackStock,current_stock:i.trackStock?i.currentStock:0,minimum_stock:i.minimumStock,status:statusFor(i)});check(error);return loadCatalog()},
  updateProduct:async(id,i)=>{const{error}=await client.from("products").update({category_id:i.categoryId,name:i.name,description:i.description,price_cents:cents(i.price),promotional_price_cents:i.promotionalPrice==null?null:cents(i.promotionalPrice),image_url:i.imageUrl,sku:i.sku,track_stock:i.trackStock,current_stock:i.trackStock?i.currentStock:0,minimum_stock:i.minimumStock,status:statusFor(i)}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()},
  deleteProduct:async(id)=>{const{error}=await client.from("products").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()},
  moveStock:async(id,type,quantity,reason)=>{const{error}=await client.rpc("adjust_stock",{p_product:id,p_type:type,p_quantity:quantity,p_reason:reason,p_key:crypto.randomUUID()});check(error);return loadCatalog()},
  createProductOption:async(i)=>{const{error}=await client.from("product_options").insert({company_id:companyId,product_id:i.productId,name:i.name,price_cents:cents(i.price),status:i.status,display_order:i.displayOrder});check(error);return loadCatalog()},
  updateProductOption:async(id,i)=>{const{error}=await client.from("product_options").update({name:i.name,price_cents:cents(i.price),status:i.status,display_order:i.displayOrder}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()},
  deleteProductOption:async(id)=>{const{error}=await client.from("product_options").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);check(error);return loadCatalog()}
 },commerce:{load:loadCommerce,createCustomer:async(i)=>{const{error}=await client.from("customers").insert({company_id:companyId,name:i.name,phone:i.phone,email:i.email,tax_id:i.taxId,address:i.address,notes:i.notes,status:i.status});check(error);return loadCommerce()},createOrder:async()=>{throw new Error("Use a RPC transacional de checkout/criação de pedido no modo Supabase.")},changeStatus:async(id,status,reason)=>{const rpc=status==="confirmed"?"confirm_order":status==="cancelled"?"cancel_order":status==="completed"?"complete_order":null;if(rpc){const args=rpc==="cancel_order"?{p_order:id,p_reason:reason??"",p_key:`cancel:${id}`}:{p_order:id,p_key:`${rpc}:${id}`};const{error}=await client.rpc(rpc,args);check(error)}else{const{error}=await client.from("orders").update({status}).eq("id",id).eq("company_id",companyId);check(error)}return loadCommerce()}},rewards:{load:async()=>({version:1,companyId,coupons:[],payments:[],program:{id:"",companyId,name:"",mode:"points",pointsPerReal:1,rewardThreshold:1,rewardDescription:"",status:"active"},accounts:[]}),createCoupon:async(i)=>{const{error}=await client.from("coupons").insert({company_id:companyId,code:i.code,type:i.type,value:i.type==="fixed"?cents(i.value):i.value,minimum_order_cents:cents(i.minimumOrder),usage_limit:i.usageLimit,starts_at:i.startsAt,expires_at:i.expiresAt,status:i.status});check(error);return (await createSupabaseRepositories(client,companyId).rewards.load())},registerPayment:async(id,m,s)=>{const{error}=await client.rpc("register_payment",{p_order:id,p_method:m,p_status:s,p_reference:null,p_key:`payment:${id}:${s}`});check(error);return (await createSupabaseRepositories(client,companyId).rewards.load())}}};}
