import test from "node:test";
import assert from "node:assert/strict";
import { CommerceService, COMMERCE_STORAGE_KEY } from "../lib/commerce-service.ts";
import { CatalogService } from "../lib/catalog-service.ts";

class MemoryStorage { data=new Map(); getItem(k){return this.data.get(k)??null} setItem(k,v){this.data.set(k,v)} }
const setup=()=>{const storage=new MemoryStorage(),catalog=new CatalogService(storage),service=new CommerceService(storage);catalog.load();service.load();return{storage,catalog,service}};
const customerInput={name:"Cliente Teste",phone:"(12) 99999-9999",email:"teste@email.com",taxId:"",address:{street:"Rua A",number:"10",complement:"",district:"Centro",city:"Caçapava",postalCode:"12280-000"},notes:"",status:"active"};
const draft=(service,catalog)=>{const customer=service.load().customers[0],product=catalog.load().products.find(p=>p.status==="available"&&p.currentStock>=2);return{customerId:customer.id,customerName:customer.name,customerPhone:customer.phone,items:[{id:"",productId:product.id,productName:product.name,unitPrice:product.price,quantity:2,additions:["Bacon"],note:"Sem cebola",total:product.price*2}],fulfillment:"pickup",discount:5,deliveryFee:0,paymentMethod:"pix",paymentStatus:"pending"};};

test("cadastra e edita cliente",()=>{const{service}=setup();let state=service.createCustomer(customerInput);const customer=state.customers.find(c=>c.name==="Cliente Teste");assert.ok(customer);state=service.updateCustomer(customer.id,{...customerInput,name:"Cliente Editado"});assert.equal(state.customers.find(c=>c.id===customer.id)?.name,"Cliente Editado");});
test("cria pedido e calcula total",()=>{const{service,catalog}=setup();const input=draft(service,catalog);const state=service.createOrder(input);const order=state.orders[0];assert.equal(order.subtotal,input.items[0].unitPrice*2);assert.equal(order.total,order.subtotal-5);assert.equal(order.number,1049);});
test("baixa estoque ao confirmar sem duplicar",()=>{const{service,catalog}=setup();let state=service.createOrder(draft(service,catalog));const order=state.orders[0],before=catalog.load().products.find(p=>p.id===order.items[0].productId).currentStock;service.changeStatus(order.id,"confirmed");assert.equal(catalog.load().products.find(p=>p.id===order.items[0].productId).currentStock,before-2);service.changeStatus(order.id,"confirmed");assert.equal(catalog.load().products.find(p=>p.id===order.items[0].productId).currentStock,before-2);});
test("cancelamento exige motivo e devolve estoque",()=>{const{service,catalog}=setup();let order=service.createOrder(draft(service,catalog)).orders[0];service.changeStatus(order.id,"confirmed");const afterConfirm=catalog.load().products.find(p=>p.id===order.items[0].productId).currentStock;assert.throws(()=>service.changeStatus(order.id,"cancelled"),/motivo/);const state=service.changeStatus(order.id,"cancelled","Cliente desistiu");assert.equal(catalog.load().products.find(p=>p.id===order.items[0].productId).currentStock,afterConfirm+2);assert.equal(state.orders.find(o=>o.id===order.id).stockApplied,false);});
test("bloqueia produto esgotado",()=>{const{service,catalog}=setup();const product=catalog.load().products.find(p=>p.trackStock);catalog.moveStock(product.id,"adjustment",0,"Teste");const customer=service.load().customers[0];assert.throws(()=>service.createOrder({customerId:customer.id,customerName:customer.name,items:[{id:"",productId:product.id,productName:product.name,unitPrice:product.price,quantity:1,additions:[],total:product.price}],fulfillment:"pickup",discount:0,deliveryFee:0,paymentMethod:"pix",paymentStatus:"pending"}),/indisponível/);});
test("persiste após recarregar",()=>{const{service,catalog,storage}=setup();service.createOrder(draft(service,catalog));assert.ok(storage.getItem(COMMERCE_STORAGE_KEY));assert.equal(new CommerceService(storage).load().orders.some(o=>o.number===1049),true);});
test("muda status do pedido",()=>{const{service,catalog}=setup();const order=service.createOrder(draft(service,catalog)).orders[0];let state=service.changeStatus(order.id,"confirmed");state=service.changeStatus(order.id,"preparing");assert.equal(state.orders.find(o=>o.id===order.id).status,"preparing");});
test("exige endereço na entrega e impede total negativo",()=>{const{service,catalog}=setup();const input=draft(service,catalog);assert.throws(()=>service.createOrder({...input,fulfillment:"delivery",deliveryAddress:{street:"",number:"",district:"",city:"",postalCode:""}}),/endereço/);assert.throws(()=>service.createOrder({...input,discount:9999}),/negativo/);});
