import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{getSupabasePublicConfig,requireSupabasePublicConfig}from"../lib/supabase/config.ts";import{previewLocalMigration,deterministicUuid}from"../lib/migration/local-to-supabase.ts";import{createLocalRepositories}from"../lib/repositories/local.ts";import{CatalogService}from"../lib/catalog-service.ts";import{CommerceService}from"../lib/commerce-service.ts";import{RewardsService}from"../lib/rewards-service.ts";import{StorefrontService}from"../lib/storefront-service.ts";
class MemoryStorage{data=new Map();getItem(k){return this.data.get(k)??null}setItem(k,v){this.data.set(k,v)}}
const setOrDeleteEnv=(key,value)=>{if(value===undefined)delete process.env[key];else process.env[key]=value};
test("modo local é padrão e Supabase exige configuração completa",()=>{const keys=["NEXT_PUBLIC_DATA_MODE","NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"];const original=Object.fromEntries(keys.map(k=>[k,process.env[k]]));try{keys.forEach(k=>delete process.env[k]);assert.equal(getSupabasePublicConfig().mode,"local");process.env.NEXT_PUBLIC_DATA_MODE="supabase";process.env.NEXT_PUBLIC_SUPABASE_URL="";process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="";assert.equal(getSupabasePublicConfig().configured,false);assert.throws(()=>requireSupabasePublicConfig(),/Configure/)}finally{keys.forEach(k=>setOrDeleteEnv(k,original[k]))}});
test("repositórios locais preservam contratos assíncronos",async()=>{const storage=new MemoryStorage(),repos=createLocalRepositories(storage),state=await repos.catalog.load();assert.equal(repos.mode,"local");assert.ok(state.products.length>=8);assert.ok((await repos.commerce.load()).orders.length>=8)});
test("repositório local de catálogo cobre editar e excluir de categoria e produto",async()=>{const storage=new MemoryStorage(),repos=createLocalRepositories(storage);await repos.catalog.load();let state=await repos.catalog.updateCategory("cat-drinks",{name:"Bebidas Geladas",description:"Atualizada",status:"active",displayOrder:4});assert.equal(state.categories.find(c=>c.id==="cat-drinks")?.name,"Bebidas Geladas");state=await repos.catalog.updateProduct("prod-8",{categoryId:"cat-drinks",name:"Coca-Cola Lata 350ml",description:"Atualizado",price:7.5,trackStock:true,currentStock:36,minimumStock:12,status:"available"});assert.equal(state.products.find(p=>p.id==="prod-8")?.price,7.5);state=await repos.catalog.deleteProduct("prod-8");state=await repos.catalog.deleteProduct("prod-9");assert.equal(state.products.some(p=>p.id==="prod-8"||p.id==="prod-9"),false);state=await repos.catalog.deleteCategory("cat-drinks");assert.equal(state.categories.some(c=>c.id==="cat-drinks"),false)});
test("prévia lê quatro chaves, mapeia IDs e é determinística",()=>{const storage=new MemoryStorage();new CatalogService(storage).load();new CommerceService(storage).load();new RewardsService(storage).load();new StorefrontService(storage).load();const a=previewLocalMigration(storage),b=previewLocalMigration(storage);assert.equal(a.warnings.length,0);assert.equal(a.fingerprint,b.fingerprint);assert.equal(deterministicUuid("prod-1"),deterministicUuid("prod-1"));assert.match(a.idMap["prod-1"],/^[0-9a-f-]{36}$/);assert.ok(a.counts.products>=8)});
test("prévia informa chaves ausentes sem executar migração",()=>{const preview=previewLocalMigration(new MemoryStorage());assert.equal(preview.warnings.length,4);assert.equal(preview.counts.orders,0)});
test("migration SQL contém entidades, RLS, índices, auditoria e RPCs",async()=>{const sql=await readFile(new URL("../supabase/migrations/202607110001_attual_one_foundation.sql",import.meta.url),"utf8");for(const table of["companies","profiles","company_users","customers","categories","products","product_options","stock_movements","orders","order_items","payments","coupons","coupon_usages","loyalty_rules","loyalty_accounts","loyalty_transactions","import_jobs","audit_logs"])assert.match(sql,new RegExp(`create table public\\.${table}`));for(const rpc of["confirm_order","cancel_order","register_payment","apply_coupon","complete_order","reverse_loyalty"])assert.match(sql,new RegExp(`function public\\.${rpc}`));assert.match(sql,/enable row level security/);assert.match(sql,/capture_audit/);assert.match(sql,/price_cents integer/);assert.match(sql,/company_id uuid not null/)});
test("arquivo de exemplo não contém URL ou chave inventada",async()=>{const env=await readFile(new URL("../.env.example",import.meta.url),"utf8");assert.match(env,/NEXT_PUBLIC_DATA_MODE=local/);assert.match(env,/NEXT_PUBLIC_SUPABASE_URL=\r?\n/);assert.match(env,/NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=\r?\n/);assert.doesNotMatch(env,/service_role|eyJ[a-zA-Z0-9_-]{20}/)});
test("migration de estoque contém RPC adjust_stock idempotente e não altera pedidos",async()=>{const sql=await readFile(new URL("../supabase/migrations/202607111000_attual_one_catalog_stock_rpc.sql",import.meta.url),"utf8");assert.match(sql,/function public\.adjust_stock/);assert.match(sql,/idempotency_key/);assert.match(sql,/is_company_member/);assert.doesNotMatch(sql,/confirm_order|cancel_order|register_payment|apply_coupon|complete_order/)});
test("seed da Hamburgueria 07 é idempotente e cobre categorias e produtos",async()=>{const sql=await readFile(new URL("../supabase/seed/hamburgueria-07-catalog.sql",import.meta.url),"utf8");assert.match(sql,/on conflict \(company_id, name\)/);assert.match(sql,/on conflict \(company_id, sku\)/);assert.match(sql,/hamburgueria-07/);for(const sku of["H07-SB","H07-CL","H07-VG","H07-CD","H07-CF","H07-FR","H07-OR","H07-CC","H07-SL"])assert.match(sql,new RegExp(sku))});
