"use client";
import Link from "next/link";
import { useState } from "react";
import { AlertCircle, ArrowRight, LockKeyhole, Mail } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import { getSupabasePublicConfig } from "@/lib/supabase/config";
export function AuthScreen({ mode }: { mode: "login" | "recover" }) {
  const config = getSupabasePublicConfig(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  const submit=async()=>{setMessage("");if(!config.configured){setMessage("Supabase ainda não foi configurado. Use o modo local ou preencha as variáveis do projeto.");return}setLoading(true);try{const supabase=createSupabaseBrowserClient();if(mode==="recover"){const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/nova-senha`});if(error)throw error;setMessage("Se o e-mail estiver cadastrado, você receberá as instruções de recuperação.")}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;window.location.assign("/")}}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível concluir.")}finally{setLoading(false)}};
  return <main className="auth-page"><section className="auth-panel"><div className="auth-brand"><span className="brand-mark"><span/></span><strong>ATTUAL ONE</strong></div><p className="eyebrow">ACESSO SEGURO</p><h1>{mode==="login"?"Entre na sua operação":"Recupere seu acesso"}</h1><p>{mode==="login"?"Use o e-mail vinculado à sua empresa.":"Enviaremos um link seguro para redefinir sua senha."}</p>{config.mode==="local"&&<div className="auth-notice"><AlertCircle/>Modo local ativo: o painel homologado continua disponível sem autenticação.</div>}<label><span>E-mail</span><div><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div></label>{mode==="login"&&<label><span>Senha</span><div><LockKeyhole/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div></label>}{message&&<div className="auth-message" role="status">{message}</div>}<button className="primary-button auth-submit" disabled={loading} onClick={submit}>{loading?"Aguarde...":mode==="login"?"Entrar":"Enviar instruções"}<ArrowRight/></button>{mode==="login"?<Link href="/recuperar-senha">Esqueci minha senha</Link>:<Link href="/login">Voltar ao login</Link>}</section></main>;
}
