"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Boxes, ChevronDown, Edit3, Package, Plus, Search, Trash2, X } from "lucide-react";
import { createRepositories } from "@/lib/repositories/factory";
import type { CatalogRepository } from "@/lib/repositories/contracts";
import { getSupabasePublicConfig } from "@/lib/supabase/config";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { CatalogState, Category, CategoryInput, Product, ProductInput, StockMovementType } from "@/lib/catalog-types";

type View = "products" | "categories" | "stock";
type Notice = { type: "success" | "error"; text: string } | null;
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const emptyProduct = (categoryId = ""): ProductInput => ({ name: "", description: "", categoryId, price: 0, imageUrl: "", sku: "", trackStock: true, currentStock: 0, minimumStock: 0, status: "available" });

export function CatalogManager({ initialView, companyId }: { initialView: View; companyId?: string }) {
  const [state, setState] = useState<CatalogState | null>(null);
  const [view, setView] = useState<View>(initialView);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [notice, setNotice] = useState<Notice>(null);
  const [productForm, setProductForm] = useState<ProductInput | null>(null);
  const [editingProduct, setEditingProduct] = useState<string | null>(null);
  const [categoryForm, setCategoryForm] = useState<CategoryInput | null>(null);
  const [editingCategory, setEditingCategory] = useState<string | null>(null);
  const [movementProduct, setMovementProduct] = useState<Product | null>(null);
  const repoRef = useRef<CatalogRepository | null>(null);

  const repo = (): CatalogRepository => { if (repoRef.current) return repoRef.current; const mode = getSupabasePublicConfig().mode; repoRef.current = mode === "supabase" && companyId ? createRepositories({ storage: window.localStorage, supabase: createSupabaseBrowserClient(), companyId }).catalog : createRepositories({ storage: window.localStorage }).catalog; return repoRef.current; };
  const inform = (type: "success" | "error", text: string) => { setNotice({ type, text }); window.setTimeout(() => setNotice(null), 3500); };

  useEffect(() => {
    repoRef.current = null;
    let cancelled = false;
    repo().load().then(s => { if (!cancelled) setState(s); }).catch(error => inform("error", error instanceof Error ? error.message : "Não foi possível carregar o catálogo."));
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [companyId]);

  const act = async (fn: () => Promise<CatalogState>, message: string) => { try { setState(await fn()); inform("success", message); return true; } catch (error) { inform("error", error instanceof Error ? error.message : "Não foi possível concluir."); return false; } };

  const filteredProducts = useMemo(() => state?.products.filter(product => {
    const text = `${product.name} ${product.sku ?? ""}`.toLowerCase();
    return text.includes(search.toLowerCase()) && (categoryFilter === "all" || product.categoryId === categoryFilter) && (statusFilter === "all" || product.status === statusFilter);
  }) ?? [], [state, search, categoryFilter, statusFilter]);

  if (!state) return <div className="page"><div className="catalog-loading">Carregando catálogo...</div></div>;
  const lowCount = state.products.filter(p => p.trackStock && p.currentStock <= p.minimumStock).length;
  const title = view === "products" ? "Produtos" : view === "categories" ? "Categorias" : "Estoque";

  const openProduct = (product?: Product) => { setEditingProduct(product?.id ?? null); setProductForm(product ? { categoryId: product.categoryId, name: product.name, description: product.description, price: product.price, promotionalPrice: product.promotionalPrice, imageUrl: product.imageUrl, sku: product.sku, trackStock: product.trackStock, currentStock: product.currentStock, minimumStock: product.minimumStock, status: product.status } : emptyProduct(state.categories[0]?.id)); };
  const saveProduct = async () => { if (!productForm) return; const ok = await act(() => editingProduct ? repo().updateProduct(editingProduct, productForm) : repo().createProduct(productForm), editingProduct ? "Produto atualizado com sucesso." : "Produto criado com sucesso."); if (ok) setProductForm(null); };
  const saveCategory = async () => { if (!categoryForm) return; const ok = await act(() => editingCategory ? repo().updateCategory(editingCategory, categoryForm) : repo().createCategory(categoryForm), editingCategory ? "Categoria atualizada com sucesso." : "Categoria criada com sucesso."); if (ok) setCategoryForm(null); };
  const removeProduct = async (product: Product) => { if (window.confirm(`Excluir “${product.name}”? Esta ação também remove seu histórico de estoque.`)) await act(() => repo().deleteProduct(product.id), "Produto excluído."); };
  const removeCategory = async (category: Category) => { if (window.confirm(`Excluir a categoria “${category.name}”?`)) await act(() => repo().deleteCategory(category.id), "Categoria excluída."); };

  return <div className="page catalog-page">
    {notice && <div className={`toast ${notice.type}`} role="status">{notice.text}<button onClick={() => setNotice(null)}><X size={15}/></button></div>}
    <section className="page-heading catalog-heading"><div><p className="eyebrow">CATÁLOGO · HAMBURGUERIA 07</p><h1>{title}</h1><p>{view === "stock" ? "Controle saldos e registre cada movimentação." : "Organize o cardápio que seus clientes encontram."}</p></div><button className="primary-button" onClick={() => view === "categories" ? (setEditingCategory(null), setCategoryForm({ name: "", description: "", status: "active", displayOrder: state.categories.length + 1 })) : view === "stock" ? setMovementProduct(state.products[0] ?? null) : openProduct()}><Plus size={18}/>{view === "categories" ? "Nova categoria" : view === "stock" ? "Movimentar estoque" : "Novo produto"}</button></section>
    <div className="catalog-tabs"><button className={view === "products" ? "active" : ""} onClick={() => setView("products")}><Package size={17}/>Produtos <em>{state.products.length}</em></button><button className={view === "categories" ? "active" : ""} onClick={() => setView("categories")}><Boxes size={17}/>Categorias <em>{state.categories.length}</em></button><button className={view === "stock" ? "active" : ""} onClick={() => setView("stock")}><AlertTriangle size={17}/>Estoque {lowCount > 0 && <em className="warning">{lowCount}</em>}</button></div>

    {view === "products" && <>
      <div className="catalog-toolbar"><label className="catalog-search"><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nome ou SKU..."/></label><Select value={categoryFilter} onChange={setCategoryFilter} options={[['all','Todas as categorias'], ...state.categories.map(c => [c.id,c.name])]}/><Select value={statusFilter} onChange={setStatusFilter} options={[["all","Todos os status"],["available","Disponível"],["out_of_stock","Esgotado"],["inactive","Inativo"]]}/></div>
      <div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Status</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{filteredProducts.map(product => { const category = state.categories.find(c => c.id === product.categoryId); const low = product.trackStock && product.currentStock <= product.minimumStock; return <tr key={product.id}><td><div className="product-cell"><span className="catalog-product-image">{product.imageUrl ? <ProductImage src={product.imageUrl} /> : <Package/>}</span><span><strong>{product.name}</strong><small>{product.sku || "Sem SKU"}</small></span></div></td><td>{category?.name}</td><td><strong>{product.promotionalPrice !== undefined ? money.format(product.promotionalPrice) : money.format(product.price)}</strong>{product.promotionalPrice !== undefined && <small className="old-price">{money.format(product.price)}</small>}</td><td><span className={low ? "stock-low" : ""}>{product.trackStock ? `${product.currentStock} un.` : "Sem controle"}</span>{low && <small className="low-label">Estoque baixo</small>}</td><td><Status status={product.status}/></td><td><div className="row-actions"><button title="Editar" onClick={() => openProduct(product)}><Edit3 size={16}/></button><button title="Excluir" className="danger" onClick={() => removeProduct(product)}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table>{filteredProducts.length === 0 && <div className="table-empty">Nenhum produto encontrado.</div>}</div>
    </>}

    {view === "categories" && <div className="category-grid">{[...state.categories].sort((a,b) => a.displayOrder - b.displayOrder).map(category => { const count = state.products.filter(p => p.categoryId === category.id).length; return <article className="category-card" key={category.id}><div className="category-order">{String(category.displayOrder).padStart(2,"0")}</div><div><div className="category-title"><h3>{category.name}</h3><span className={category.status}>{category.status === "active" ? "Ativa" : "Inativa"}</span></div><p>{category.description || "Sem descrição"}</p><small>{count} {count === 1 ? "produto" : "produtos"}</small></div><div className="row-actions"><button title="Editar" onClick={() => { setEditingCategory(category.id); setCategoryForm({ name: category.name, description: category.description, status: category.status, displayOrder: category.displayOrder }); }}><Edit3 size={16}/></button><button title="Excluir" className="danger" onClick={() => removeCategory(category)}><Trash2 size={16}/></button></div></article>})}</div>}

    {view === "stock" && <><div className="stock-summary"><article><span>Itens controlados</span><strong>{state.products.filter(p=>p.trackStock).length}</strong></article><article><span>Estoque baixo</span><strong className="orange-text">{lowCount}</strong></article><article><span>Produtos esgotados</span><strong className="red-text">{state.products.filter(p=>p.status === "out_of_stock").length}</strong></article><article><span>Movimentações</span><strong>{state.movements.length}</strong></article></div><div className="catalog-table-wrap"><table className="catalog-table stock-table"><thead><tr><th>Produto</th><th>Saldo atual</th><th>Mínimo</th><th>Situação</th><th>Última movimentação</th><th></th></tr></thead><tbody>{state.products.filter(p=>p.trackStock).map(product => { const last = state.movements.find(m=>m.productId===product.id); const low = product.currentStock <= product.minimumStock; return <tr key={product.id}><td><div className="product-cell"><span className="catalog-product-image"><Package/></span><span><strong>{product.name}</strong><small>{product.sku}</small></span></div></td><td><strong>{product.currentStock} un.</strong></td><td>{product.minimumStock} un.</td><td>{low ? <span className="low-label visible"><AlertTriangle size={13}/> {product.currentStock === 0 ? "Esgotado" : "Estoque baixo"}</span> : <span className="ok-label">Normal</span>}</td><td>{last ? <><strong className="movement-reason">{last.reason}</strong><small className="movement-date">{new Date(last.createdAt).toLocaleString("pt-BR")}</small></> : <span className="muted">Sem movimentação</span>}</td><td><button className="outline-button" onClick={()=>setMovementProduct(product)}>Movimentar</button></td></tr>})}</tbody></table></div><section className="movement-history panel"><div className="panel-header"><div><h2>Histórico de movimentações</h2><p>Rastreabilidade das alterações de saldo</p></div></div>{state.movements.length === 0 ? <div className="table-empty">Nenhuma movimentação registrada ainda.</div> : state.movements.slice(0,10).map(m => { const product=state.products.find(p=>p.id===m.productId); return <div className="movement-row" key={m.id}><span className={`movement-type ${m.type}`}>{m.type === "entry" ? "+" : m.type === "exit" ? "−" : "="}</span><span><strong>{product?.name}</strong><small>{m.reason}</small></span><span><strong>{m.previousStock} → {m.resultingStock}</strong><small>{new Date(m.createdAt).toLocaleString("pt-BR")}</small></span></div>})}</section></>}

    {productForm && <ProductModal value={productForm} categories={state.categories} editing={Boolean(editingProduct)} onChange={setProductForm} onClose={()=>setProductForm(null)} onSave={saveProduct}/>} 
    {categoryForm && <CategoryModal value={categoryForm} editing={Boolean(editingCategory)} onChange={setCategoryForm} onClose={()=>setCategoryForm(null)} onSave={saveCategory}/>} 
    {movementProduct && <MovementModal product={movementProduct} onClose={()=>setMovementProduct(null)} onSave={async (type, quantity, reason) => { const ok = await act(() => repo().moveStock(movementProduct.id, type, quantity, reason), "Estoque atualizado com sucesso."); if (ok) setMovementProduct(null); }}/>}
  </div>;
}

function Select({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:string[][]}) { return <label className="catalog-select"><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><ChevronDown size={15}/></label>; }
function ProductImage({ src }: { src: string }) { return <span className="remote-product-image" style={{ backgroundImage: `url(${src})` }} role="img" aria-label="Imagem do produto" />; }
function Status({status}:{status:Product["status"]}) { const labels={available:"Disponível",out_of_stock:"Esgotado",inactive:"Inativo"}; return <span className={`catalog-status ${status}`}><i/>{labels[status]}</span>; }
function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:React.ReactNode;footer:React.ReactNode}) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">HAMBURGUERIA 07</p><h2>{title}</h2></div><button onClick={onClose} aria-label="Fechar janela"><X/></button></header><div className="modal-body">{children}</div><footer>{footer}</footer></section></div>; }
function Field({label,required,children,wide}:{label:string;required?:boolean;children:React.ReactNode;wide?:boolean}) { return <label className={`form-field ${wide?"wide":""}`}><span>{label}{required&&<em>*</em>}</span>{children}</label>; }
function ProductModal({value,categories,editing,onChange,onClose,onSave}:{value:ProductInput;categories:Category[];editing:boolean;onChange:(v:ProductInput)=>void;onClose:()=>void;onSave:()=>void}) { const set=<K extends keyof ProductInput>(key:K,val:ProductInput[K])=>onChange({...value,[key]:val}); return <Modal title={editing?"Editar produto":"Novo produto"} onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={onSave}>Salvar produto</button></>}><div className="form-grid"><Field label="Nome" required wide><input value={value.name} onChange={e=>set("name",e.target.value)} placeholder="Ex.: Smash Bacon"/></Field><Field label="Descrição" wide><textarea value={value.description} onChange={e=>set("description",e.target.value)} rows={3}/></Field><Field label="Categoria" required><select value={value.categoryId} onChange={e=>set("categoryId",e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="SKU"><input value={value.sku||""} onChange={e=>set("sku",e.target.value)}/></Field><Field label="Preço" required><input type="number" min="0" step="0.01" value={value.price} onChange={e=>set("price",Number(e.target.value))}/></Field><Field label="Preço promocional"><input type="number" min="0" step="0.01" value={value.promotionalPrice??""} onChange={e=>set("promotionalPrice",e.target.value===""?undefined:Number(e.target.value))}/></Field><Field label="Imagem por URL" wide><input type="url" value={value.imageUrl||""} onChange={e=>set("imageUrl",e.target.value)} placeholder="https://..."/></Field><Field label="Status"><select value={value.status} onChange={e=>set("status",e.target.value as Product["status"])}><option value="available">Disponível</option><option value="out_of_stock">Esgotado</option><option value="inactive">Inativo</option></select></Field><Field label="Controle de estoque"><label className="switch-row"><input type="checkbox" checked={value.trackStock} onChange={e=>set("trackStock",e.target.checked)}/><span>Controlar saldo</span></label></Field>{value.trackStock&&<><Field label="Estoque atual"><input type="number" min="0" value={value.currentStock} onChange={e=>set("currentStock",Number(e.target.value))}/></Field><Field label="Estoque mínimo"><input type="number" min="0" value={value.minimumStock} onChange={e=>set("minimumStock",Number(e.target.value))}/></Field></>}</div></Modal>; }
function CategoryModal({value,editing,onChange,onClose,onSave}:{value:CategoryInput;editing:boolean;onChange:(v:CategoryInput)=>void;onClose:()=>void;onSave:()=>void}) { return <Modal title={editing?"Editar categoria":"Nova categoria"} onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={onSave}>Salvar categoria</button></>}><div className="form-grid"><Field label="Nome" required wide><input value={value.name} onChange={e=>onChange({...value,name:e.target.value})}/></Field><Field label="Descrição" wide><textarea rows={3} value={value.description||""} onChange={e=>onChange({...value,description:e.target.value})}/></Field><Field label="Status"><select value={value.status} onChange={e=>onChange({...value,status:e.target.value as Category["status"]})}><option value="active">Ativa</option><option value="inactive">Inativa</option></select></Field><Field label="Ordem de exibição"><input type="number" min="0" value={value.displayOrder} onChange={e=>onChange({...value,displayOrder:Number(e.target.value)})}/></Field></div></Modal>; }
function MovementModal({product,onClose,onSave}:{product:Product;onClose:()=>void;onSave:(type:StockMovementType,quantity:number,reason:string)=>void}) { const [type,setType]=useState<StockMovementType>("entry"); const [quantity,setQuantity]=useState(1); const [reason,setReason]=useState(""); return <Modal title={`Movimentar: ${product.name}`} onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={()=>onSave(type,quantity,reason)}>Confirmar movimentação</button></>}><div className="current-balance"><span>Saldo atual</span><strong>{product.currentStock} unidades</strong></div><div className="movement-tabs"><button className={type==="entry"?"active":""} onClick={()=>setType("entry")}>Entrada</button><button className={type==="exit"?"active":""} onClick={()=>setType("exit")}>Saída</button><button className={type==="adjustment"?"active":""} onClick={()=>setType("adjustment")}>Ajuste</button></div><div className="form-grid"><Field label={type==="adjustment"?"Novo saldo":"Quantidade"} required><input type="number" min="0" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></Field><Field label="Motivo" required wide><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: Recebimento do fornecedor"/></Field></div></Modal>; }
