"use client";
import { useEffect,useMemo,useState } from "react";
import {BadgePercent,CreditCard,Edit3,Gift,Plus,Search,Trash2,Trophy,X} from "lucide-react";
import {createBrowserRewardsService} from "@/lib/rewards-service";
import {createBrowserCommerceService} from "@/lib/commerce-service";
import type {CommerceState,PaymentMethod,PaymentStatus} from "@/lib/commerce-types";
import type {Coupon,CouponInput,LoyaltyMode,RewardsState} from "@/lib/rewards-types";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
type Tab="payments"|"coupons"|"loyalty";type Notice={type:"success"|"error";text:string}|null;
const emptyCoupon=():CouponInput=>({code:"",description:"",type:"percentage",value:10,minimumOrder:0,usageLimit:undefined,startsAt:"2026-07-10",expiresAt:"2026-12-31",status:"active"});
export function RewardsManager({initialTab}:{initialTab:Tab}){const[state,setState]=useState<RewardsState|null>(null),[commerce,setCommerce]=useState<CommerceState|null>(null),[tab,setTab]=useState(initialTab),[search,setSearch]=useState(""),[notice,setNotice]=useState<Notice>(null),[couponForm,setCouponForm]=useState<CouponInput|null>(null),[editing,setEditing]=useState<string|null>(null),[paymentOrder,setPaymentOrder]=useState<string|null>(null);
 useEffect(()=>{const t=setTimeout(()=>{setState(createBrowserRewardsService().syncLoyalty());setCommerce(createBrowserCommerceService().load())},0);return()=>clearTimeout(t)},[]);const inform=(type:"success"|"error",text:string)=>{setNotice({type,text});setTimeout(()=>setNotice(null),3500)};const act=(fn:()=>RewardsState,msg:string)=>{try{setState(fn());setCommerce(createBrowserCommerceService().load());inform("success",msg);return true}catch(e){inform("error",e instanceof Error?e.message:"Não foi possível concluir.");return false}};
 const filteredPayments=useMemo(()=>state?.payments.filter(p=>`${p.orderNumber} ${p.customerName}`.toLowerCase().includes(search.toLowerCase()))??[],[state,search]);if(!state||!commerce)return <div className="page"><div className="catalog-loading">Carregando financeiro...</div></div>;
 const saveCoupon=()=>{if(!couponForm)return;const ok=act(()=>editing?createBrowserRewardsService().updateCoupon(editing,couponForm):createBrowserRewardsService().createCoupon(couponForm),editing?"Cupom atualizado.":"Cupom criado.");if(ok)setCouponForm(null)};const openCoupon=(c?:Coupon)=>{setEditing(c?.id??null);setCouponForm(c?{code:c.code,description:c.description,type:c.type,value:c.value,minimumOrder:c.minimumOrder,usageLimit:c.usageLimit,startsAt:c.startsAt,expiresAt:c.expiresAt,status:c.status}:emptyCoupon())};
 const pendingOrders=commerce.orders.filter(o=>o.status!=="cancelled");return <div className="page rewards-page">{notice&&<div className={`toast ${notice.type}`}>{notice.text}<button onClick={()=>setNotice(null)}><X size={15}/></button></div>}<section className="page-heading catalog-heading"><div><p className="eyebrow">RELACIONAMENTO · HAMBURGUERIA 07</p><h1>{tab==="payments"?"Pagamentos":"Cupons e fidelidade"}</h1><p>Controle recebimentos e recompense seus melhores clientes.</p></div><button className="primary-button" onClick={()=>tab==="payments"?setPaymentOrder(pendingOrders[0]?.id??null):tab==="coupons"?openCoupon():setState(createBrowserRewardsService().syncLoyalty())}><Plus size={18}/>{tab==="payments"?"Registrar pagamento":tab==="coupons"?"Novo cupom":"Atualizar saldos"}</button></section>
 <div className="catalog-tabs"><button className={tab==="payments"?"active":""} onClick={()=>setTab("payments")}><CreditCard size={17}/>Pagamentos</button><button className={tab==="coupons"?"active":""} onClick={()=>setTab("coupons")}><BadgePercent size={17}/>Cupons</button><button className={tab==="loyalty"?"active":""} onClick={()=>setTab("loyalty")}><Gift size={17}/>Fidelidade</button></div>
 {tab==="payments"&&<><div className="rewards-summary"><article><span>Recebido</span><strong>{money.format(state.payments.filter(p=>p.status==="paid").reduce((s,p)=>s+p.amount,0))}</strong></article><article><span>Pendente</span><strong>{money.format(state.payments.filter(p=>p.status==="pending").reduce((s,p)=>s+p.amount,0))}</strong></article><article><span>Transações</span><strong>{state.payments.length}</strong></article></div><label className="catalog-search rewards-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por pedido ou cliente..."/></label><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Valor</th><th>Forma</th><th>Status</th><th>Atualização</th></tr></thead><tbody>{filteredPayments.map(p=><tr key={p.id}><td><strong>#{p.orderNumber}</strong></td><td>{p.customerName}</td><td><strong>{money.format(p.amount)}</strong></td><td>{methodLabel(p.method)}</td><td><span className={`payment-state ${p.status}`}>{paymentLabel(p.status)}</span></td><td>{new Date(p.updatedAt).toLocaleString("pt-BR")}</td></tr>)}</tbody></table>{!filteredPayments.length&&<div className="table-empty">Nenhum pagamento registrado.</div>}</div></>}
 {tab==="coupons"&&<div className="coupon-grid">{state.coupons.map(c=><article className={`coupon-card ${c.status}`} key={c.id}><div className="coupon-mark"><BadgePercent/></div><div><span className="coupon-code">{c.code}</span><h3>{c.description||"Cupom promocional"}</h3><p>{c.type==="percentage"?`${c.value}% de desconto`:`${money.format(c.value)} de desconto`} · mínimo {money.format(c.minimumOrder)}</p><small>Válido até {new Date(`${c.expiresAt}T12:00:00`).toLocaleDateString("pt-BR")} · {c.usageCount} usos</small></div><div className="row-actions"><button onClick={()=>openCoupon(c)}><Edit3 size={15}/></button><button className="danger" onClick={()=>{if(confirm(`Excluir o cupom ${c.code}?`))act(()=>createBrowserRewardsService().deleteCoupon(c.id),"Cupom excluído.")}}><Trash2 size={15}/></button></div></article>)}</div>}
 {tab==="loyalty"&&<><section className="loyalty-hero"><span><Trophy/></span><div><p className="eyebrow">PROGRAMA ATIVO</p><h2>{state.program.name}</h2><p>{state.program.mode==="points"?`${state.program.pointsPerReal} ponto por real · recompensa a cada ${state.program.rewardThreshold} pontos`:`Recompensa a cada ${state.program.rewardThreshold} compras`} — {state.program.rewardDescription}</p></div><ProgramEditor state={state} onSave={(mode,rate,threshold,reward)=>act(()=>createBrowserRewardsService().updateProgram(mode,rate,threshold,reward),"Programa atualizado.")}/></section><div className="loyalty-grid">{state.accounts.sort((a,b)=>b.points-a.points).map((a,i)=><article key={a.id}><span className="loyalty-rank">{i+1}</span><span className="customer-avatar">{a.customerName.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><span><strong>{a.customerName}</strong><small>{a.purchaseCount} compras</small></span><span><strong>{state.program.mode==="points"?`${a.points} pts`:`${a.purchaseCount} selos`}</strong><small>{a.rewardsAvailable} recompensas</small></span></article>)}</div></>}
 {couponForm&&<CouponModal value={couponForm} editing={!!editing} onChange={setCouponForm} onSave={saveCoupon} onClose={()=>setCouponForm(null)}/>} {paymentOrder&&<PaymentModal orderId={paymentOrder} orders={pendingOrders} onClose={()=>setPaymentOrder(null)} onSave={(id,m,s,r,n)=>{const ok=act(()=>createBrowserRewardsService().registerPayment(id,m,s,r,n),"Pagamento registrado.");if(ok)setPaymentOrder(null)}}/>}</div>}
function methodLabel(v:PaymentMethod){return{pix:"Pix",cash:"Dinheiro",credit_card:"Crédito",debit_card:"Débito"}[v]}function paymentLabel(v:PaymentStatus){return{pending:"Pendente",paid:"Pago",refunded:"Estornado"}[v]}
function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:React.ReactNode;footer:React.ReactNode}){return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar janela"><X/></button></header><div className="modal-body">{children}</div><footer>{footer}</footer></section></div>}
function CouponModal({value,editing,onChange,onSave,onClose}:{value:CouponInput;editing:boolean;onChange:(v:CouponInput)=>void;onSave:()=>void;onClose:()=>void}){return <Modal title={editing?"Editar cupom":"Novo cupom"} onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={onSave}>Salvar cupom</button></>}><div className="form-grid"><Field l="Código"><input value={value.code} onChange={e=>onChange({...value,code:e.target.value.toUpperCase()})}/></Field><Field l="Tipo"><select value={value.type} onChange={e=>onChange({...value,type:e.target.value as Coupon["type"]})}><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></Field><Field l="Descrição" wide><input value={value.description??""} onChange={e=>onChange({...value,description:e.target.value})}/></Field><Field l="Valor"><input type="number" min="0" value={value.value} onChange={e=>onChange({...value,value:Number(e.target.value)})}/></Field><Field l="Pedido mínimo"><input type="number" min="0" value={value.minimumOrder} onChange={e=>onChange({...value,minimumOrder:Number(e.target.value)})}/></Field><Field l="Início"><input type="date" value={value.startsAt} onChange={e=>onChange({...value,startsAt:e.target.value})}/></Field><Field l="Validade"><input type="date" value={value.expiresAt} onChange={e=>onChange({...value,expiresAt:e.target.value})}/></Field><Field l="Status"><select value={value.status} onChange={e=>onChange({...value,status:e.target.value as Coupon["status"]})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></Field></div></Modal>}
function PaymentModal({orderId,orders,onClose,onSave}:{orderId:string;orders:CommerceState["orders"];onClose:()=>void;onSave:(id:string,m:PaymentMethod,s:PaymentStatus,r:string,n:string)=>void}){const[id,setId]=useState(orderId),[method,setMethod]=useState<PaymentMethod>("pix"),[status,setStatus]=useState<PaymentStatus>("paid"),[reference,setReference]=useState(""),[notes,setNotes]=useState("");return <Modal title="Registrar pagamento" onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={()=>onSave(id,method,status,reference,notes)}>Salvar pagamento</button></>}><div className="form-grid"><Field l="Pedido" wide><select value={id} onChange={e=>setId(e.target.value)}>{orders.map(o=><option key={o.id} value={o.id}>#{o.number} · {o.customerName} · {money.format(o.total)}</option>)}</select></Field><Field l="Forma"><select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Crédito</option><option value="debit_card">Débito</option></select></Field><Field l="Status"><select value={status} onChange={e=>setStatus(e.target.value as PaymentStatus)}><option value="paid">Pago</option><option value="pending">Pendente</option><option value="refunded">Estornado</option></select></Field><Field l="Referência" wide><input value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field l="Observações" wide><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div></Modal>}
function Field({l,children,wide}:{l:string;children:React.ReactNode;wide?:boolean}){return <label className={`form-field ${wide?"wide":""}`}><span>{l}</span>{children}</label>}
function ProgramEditor({state,onSave}:{state:RewardsState;onSave:(m:LoyaltyMode,r:number,t:number,d:string)=>void}){const[m,setM]=useState(state.program.mode),[r,setR]=useState(state.program.pointsPerReal),[t,setT]=useState(state.program.rewardThreshold),[d,setD]=useState(state.program.rewardDescription);return <div className="program-editor"><select value={m} onChange={e=>setM(e.target.value as LoyaltyMode)}><option value="points">Pontos</option><option value="buy_and_get">Compre e ganhe</option></select><input type="number" value={r} onChange={e=>setR(Number(e.target.value))}/><input type="number" value={t} onChange={e=>setT(Number(e.target.value))}/><input value={d} onChange={e=>setD(e.target.value)}/><button onClick={()=>onSave(m,r,t,d)}>Salvar</button></div>}
