"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import {BadgePercent,CreditCard,Edit3,Gift,Plus,RotateCcw,Search,Trash2,Trophy,X} from "lucide-react";
import {createRepositories} from "@/lib/repositories/factory";
import type {RepositorySet} from "@/lib/repositories/contracts";
import {getSupabasePublicConfig} from "@/lib/supabase/config";
import {createSupabaseBrowserClient} from "@/lib/supabase/browser";
import type {CommerceState,PaymentMethod,PaymentStatus} from "@/lib/commerce-types";
import type {Coupon,CouponInput,LoyaltyMode,Payment,RewardsState} from "@/lib/rewards-types";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
type Tab="payments"|"coupons"|"loyalty";type Notice={type:"success"|"error";text:string}|null;
const emptyCoupon=():CouponInput=>({code:"",description:"",type:"percentage",value:10,minimumOrder:0,usageLimit:undefined,perCustomerLimit:undefined,startsAt:"2026-07-10",expiresAt:"2026-12-31",status:"active"});
export function RewardsManager({initialTab,companyId}:{initialTab:Tab;companyId?:string}){const[state,setState]=useState<RewardsState|null>(null),[commerce,setCommerce]=useState<CommerceState|null>(null),[tab,setTab]=useState(initialTab),[search,setSearch]=useState(""),[notice,setNotice]=useState<Notice>(null),[couponForm,setCouponForm]=useState<CouponInput|null>(null),[editing,setEditing]=useState<string|null>(null),[paymentOrder,setPaymentOrder]=useState<string|null>(null),[refunding,setRefunding]=useState<Payment|null>(null);
 const repoRef=useRef<RepositorySet|null>(null);
 const repo=():RepositorySet=>{if(repoRef.current)return repoRef.current;const mode=getSupabasePublicConfig().mode;repoRef.current=mode==="supabase"&&companyId?createRepositories({storage:window.localStorage,supabase:createSupabaseBrowserClient(),companyId}):createRepositories({storage:window.localStorage});return repoRef.current};
 const inform=(type:"success"|"error",text:string)=>{setNotice({type,text});setTimeout(()=>setNotice(null),3500)};
 useEffect(()=>{
  repoRef.current=null;let cancelled=false;const r=repo();
  Promise.all([r.rewards.syncLoyalty?r.rewards.syncLoyalty():r.rewards.load(),r.commerce.load()]).then(([s,c])=>{if(!cancelled){setState(s);setCommerce(c)}}).catch(e=>inform("error",e instanceof Error?e.message:"Não foi possível carregar o financeiro."));
  return()=>{cancelled=true};
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[companyId]);
 const act=async(fn:()=>Promise<RewardsState>,msg:string):Promise<RewardsState|null>=>{try{const result=await fn();setState(result);setCommerce(await repo().commerce.load());inform("success",msg);return result}catch(e){inform("error",e instanceof Error?e.message:"Não foi possível concluir.");return null}};
 const filteredPayments=useMemo(()=>state?.payments.filter(p=>`${p.orderNumber} ${p.customerName}`.toLowerCase().includes(search.toLowerCase()))??[],[state,search]);if(!state||!commerce)return <div className="page"><div className="catalog-loading">Carregando financeiro...</div></div>;
 const saveCoupon=async()=>{if(!couponForm)return;const result=await act(()=>editing?repo().rewards.updateCoupon(editing,couponForm):repo().rewards.createCoupon(couponForm),editing?"Cupom atualizado.":"Cupom criado.");if(result)setCouponForm(null)};const openCoupon=(c?:Coupon)=>{setEditing(c?.id??null);setCouponForm(c?{code:c.code,description:c.description,type:c.type,value:c.value,minimumOrder:c.minimumOrder,usageLimit:c.usageLimit,perCustomerLimit:c.perCustomerLimit,startsAt:c.startsAt,expiresAt:c.expiresAt,status:c.status}:emptyCoupon())};
 const removeCoupon=async(c:Coupon)=>{if(confirm(`Excluir o cupom ${c.code}?`))await act(()=>repo().rewards.deleteCoupon(c.id),"Cupom excluído.")};
 const refreshLoyalty=async()=>{const r=repo();await act(()=>r.rewards.syncLoyalty?r.rewards.syncLoyalty():r.rewards.load(),"Saldos atualizados.")};
 const pendingOrders=commerce.orders.filter(o=>o.status!=="cancelled");return <div className="page rewards-page">{notice&&<div className={`toast ${notice.type}`}>{notice.text}<button onClick={()=>setNotice(null)}><X size={15}/></button></div>}<section className="page-heading catalog-heading"><div><p className="eyebrow">RELACIONAMENTO · HAMBURGUERIA 07</p><h1>{tab==="payments"?"Pagamentos":"Cupons e fidelidade"}</h1><p>Controle recebimentos e recompense seus melhores clientes.</p></div><button className="primary-button" onClick={()=>tab==="payments"?setPaymentOrder(pendingOrders[0]?.id??null):tab==="coupons"?openCoupon():refreshLoyalty()}><Plus size={18}/>{tab==="payments"?"Registrar pagamento":tab==="coupons"?"Novo cupom":"Atualizar saldos"}</button></section>
 <div className="catalog-tabs"><button className={tab==="payments"?"active":""} onClick={()=>setTab("payments")}><CreditCard size={17}/>Pagamentos</button><button className={tab==="coupons"?"active":""} onClick={()=>setTab("coupons")}><BadgePercent size={17}/>Cupons</button><button className={tab==="loyalty"?"active":""} onClick={()=>setTab("loyalty")}><Gift size={17}/>Fidelidade</button></div>
 {tab==="payments"&&<><div className="rewards-summary"><article><span>Recebido</span><strong>{money.format(state.payments.reduce((s,p)=>s+(p.status==="paid"||p.status==="refunded"?p.amount-(p.refundedAmount??0):0),0))}</strong></article><article><span>Pendente</span><strong>{money.format(state.payments.filter(p=>p.status==="pending"||p.status==="partial").reduce((s,p)=>s+p.amount,0))}</strong></article><article><span>Transações</span><strong>{state.payments.length}</strong></article></div><label className="catalog-search rewards-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por pedido ou cliente..."/></label><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Valor</th><th>Forma</th><th>Status</th><th>Atualização</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{filteredPayments.map(p=><tr key={p.id}><td><strong>#{p.orderNumber}</strong></td><td>{p.customerName}</td><td><strong>{money.format(p.amount)}</strong>{!!p.refundedAmount&&<small className="old-price">Estornado: {money.format(p.refundedAmount)}</small>}</td><td>{methodLabel(p.method)}</td><td><span className={`payment-state ${p.status}`}>{paymentLabel(p.status)}</span></td><td>{new Date(p.updatedAt).toLocaleString("pt-BR")}</td><td>{p.status==="paid"&&<button className="outline-button" title="Estornar" onClick={()=>setRefunding(p)}><RotateCcw size={14}/> Estornar</button>}</td></tr>)}</tbody></table>{!filteredPayments.length&&<div className="table-empty">Nenhum pagamento registrado.</div>}</div>{state.paymentRefunds&&state.paymentRefunds.length>0&&<section className="movement-history panel"><div className="panel-header"><div><h2>Histórico de estornos</h2><p>Estornos totais e parciais recentes</p></div></div>{state.paymentRefunds.map(r=><div className="movement-row" key={r.id}><span className="movement-type exit">−</span><span><strong>#{r.orderNumber} · {r.customerName}</strong><small>{r.reason}</small></span><span><strong>{money.format(r.amount)}</strong><small>{new Date(r.createdAt).toLocaleString("pt-BR")}</small></span></div>)}</section>}</>}
 {tab==="coupons"&&<div className="coupon-grid">{state.coupons.map(c=><article className={`coupon-card ${c.status}`} key={c.id}><div className="coupon-mark"><BadgePercent/></div><div><span className="coupon-code">{c.code}</span><h3>{c.description||"Cupom promocional"}</h3><p>{c.type==="percentage"?`${c.value}% de desconto`:`${money.format(c.value)} de desconto`} · mínimo {money.format(c.minimumOrder)}</p><small>Válido até {new Date(`${c.expiresAt}T12:00:00`).toLocaleDateString("pt-BR")} · {c.usageCount} usos{c.perCustomerLimit?` · limite ${c.perCustomerLimit}/cliente`:""}</small></div><div className="row-actions"><button onClick={()=>openCoupon(c)}><Edit3 size={15}/></button><button className="danger" onClick={()=>removeCoupon(c)}><Trash2 size={15}/></button></div></article>)}</div>}
 {tab==="loyalty"&&<><section className="loyalty-hero"><span><Trophy/></span><div><p className="eyebrow">PROGRAMA ATIVO</p><h2>{state.program.name}</h2><p>{state.program.mode==="points"?`${state.program.pointsPerReal} ponto por real · recompensa a cada ${state.program.rewardThreshold} pontos`:`Recompensa a cada ${state.program.rewardThreshold} compras`} — {state.program.rewardDescription}</p></div><ProgramEditor state={state} onSave={async(mode,rate,threshold,reward)=>{await act(()=>repo().rewards.updateProgram(mode,rate,threshold,reward),"Programa atualizado.")}}/></section><div className="loyalty-grid">{state.accounts.sort((a,b)=>b.points-a.points).map((a,i)=><article key={a.id}><span className="loyalty-rank">{i+1}</span><span className="customer-avatar">{a.customerName.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><span><strong>{a.customerName}</strong><small>{a.purchaseCount} compras</small></span><span><strong>{state.program.mode==="points"?`${a.points} pts`:`${a.purchaseCount} selos`}</strong><small>{a.rewardsAvailable} recompensas</small></span></article>)}</div>{state.loyaltyTransactions&&state.loyaltyTransactions.length>0&&<section className="movement-history panel"><div className="panel-header"><div><h2>Histórico de fidelidade</h2><p>Créditos, resgates e estornos recentes</p></div></div>{state.loyaltyTransactions.map(t=><div className="movement-row" key={t.id}><span className={`movement-type ${t.type==="credit"?"entry":t.type==="reversal"?"exit":"adjustment"}`}>{t.type==="credit"?"+":t.type==="reversal"?"−":"="}</span><span><strong>{t.customerName}</strong><small>{t.reason}</small></span><span><strong>{t.points!==0?`${t.points>0?"+":""}${t.points} pts`:t.rewards!==0?`${t.rewards>0?"+":""}${t.rewards} recompensa(s)`:"—"}</strong><small>{new Date(t.createdAt).toLocaleString("pt-BR")}</small></span></div>)}</section>}</>}
 {couponForm&&<CouponModal value={couponForm} editing={!!editing} onChange={setCouponForm} onSave={saveCoupon} onClose={()=>setCouponForm(null)}/>} {paymentOrder&&<PaymentModal orderId={paymentOrder} orders={pendingOrders} onClose={()=>setPaymentOrder(null)} onSave={async(id,m,s,r,n)=>{const result=await act(()=>repo().rewards.registerPayment(id,m,s,r,n),"Pagamento registrado.");if(result)setPaymentOrder(null)}}/>} {refunding&&<RefundModal payment={refunding} onClose={()=>setRefunding(null)} onSave={async(amount,reason,fullRefund)=>{const result=await act(()=>repo().rewards.refundPayment(refunding.id,amount,reason,fullRefund),"Estorno registrado.");if(result)setRefunding(null)}}/>}</div>}
function methodLabel(v:PaymentMethod){return{pix:"Pix",cash:"Dinheiro",credit_card:"Crédito",debit_card:"Débito"}[v]}function paymentLabel(v:PaymentStatus){return{pending:"Pendente",paid:"Pago",partial:"Parcial",refunded:"Estornado"}[v]}
function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:React.ReactNode;footer:React.ReactNode}){return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar janela"><X/></button></header><div className="modal-body">{children}</div><footer>{footer}</footer></section></div>}
function CouponModal({value,editing,onChange,onSave,onClose}:{value:CouponInput;editing:boolean;onChange:(v:CouponInput)=>void;onSave:()=>void;onClose:()=>void}){return <Modal title={editing?"Editar cupom":"Novo cupom"} onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={onSave}>Salvar cupom</button></>}><div className="form-grid"><Field l="Código"><input value={value.code} onChange={e=>onChange({...value,code:e.target.value.toUpperCase()})}/></Field><Field l="Tipo"><select value={value.type} onChange={e=>onChange({...value,type:e.target.value as Coupon["type"]})}><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></Field><Field l="Descrição" wide><input value={value.description??""} onChange={e=>onChange({...value,description:e.target.value})}/></Field><Field l="Valor"><input type="number" min="0" value={value.value} onChange={e=>onChange({...value,value:Number(e.target.value)})}/></Field><Field l="Pedido mínimo"><input type="number" min="0" value={value.minimumOrder} onChange={e=>onChange({...value,minimumOrder:Number(e.target.value)})}/></Field><Field l="Limite total de usos"><input type="number" min="0" value={value.usageLimit??""} onChange={e=>onChange({...value,usageLimit:e.target.value===""?undefined:Number(e.target.value)})}/></Field><Field l="Limite por cliente"><input type="number" min="0" value={value.perCustomerLimit??""} onChange={e=>onChange({...value,perCustomerLimit:e.target.value===""?undefined:Number(e.target.value)})}/></Field><Field l="Início"><input type="date" value={value.startsAt} onChange={e=>onChange({...value,startsAt:e.target.value})}/></Field><Field l="Validade"><input type="date" value={value.expiresAt} onChange={e=>onChange({...value,expiresAt:e.target.value})}/></Field><Field l="Status"><select value={value.status} onChange={e=>onChange({...value,status:e.target.value as Coupon["status"]})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></Field></div></Modal>}
function PaymentModal({orderId,orders,onClose,onSave}:{orderId:string;orders:CommerceState["orders"];onClose:()=>void;onSave:(id:string,m:PaymentMethod,s:PaymentStatus,r:string,n:string)=>void}){const[id,setId]=useState(orderId),[method,setMethod]=useState<PaymentMethod>("pix"),[status,setStatus]=useState<PaymentStatus>("paid"),[reference,setReference]=useState(""),[notes,setNotes]=useState("");return <Modal title="Registrar pagamento" onClose={onClose} footer={<><button className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={()=>onSave(id,method,status,reference,notes)}>Salvar pagamento</button></>}><div className="form-grid"><Field l="Pedido" wide><select value={id} onChange={e=>setId(e.target.value)}>{orders.map(o=><option key={o.id} value={o.id}>#{o.number} · {o.customerName} · {money.format(o.total)}</option>)}</select></Field><Field l="Forma"><select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Crédito</option><option value="debit_card">Débito</option></select></Field><Field l="Status"><select value={status} onChange={e=>setStatus(e.target.value as PaymentStatus)}><option value="paid">Pago</option><option value="pending">Pendente</option><option value="refunded">Estornado</option></select></Field><Field l="Referência" wide><input value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field l="Observações" wide><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div></Modal>}
function Field({l,children,wide}:{l:string;children:React.ReactNode;wide?:boolean}){return <label className={`form-field ${wide?"wide":""}`}><span>{l}</span>{children}</label>}
function RefundModal({payment,onClose,onSave}:{payment:Payment;onClose:()=>void;onSave:(amount:number,reason:string,fullRefund:boolean)=>Promise<void>}){const refundable=Math.max(0,payment.amount-(payment.refundedAmount??0));const[full,setFull]=useState(true);const[amount,setAmount]=useState(refundable);const[reason,setReason]=useState("");const[submitting,setSubmitting]=useState(false);const effectiveAmount=full?refundable:amount;const valid=reason.trim().length>0&&effectiveAmount>0&&effectiveAmount<=refundable+0.001;const confirm=async()=>{if(!valid||submitting)return;setSubmitting(true);try{await onSave(effectiveAmount,reason.trim(),full)}finally{setSubmitting(false)}};return <Modal title={`Estornar pagamento #${payment.orderNumber}`} onClose={onClose} footer={<><button className="text-button" onClick={onClose} disabled={submitting}>Cancelar</button><button className="primary-button" disabled={!valid||submitting} onClick={confirm}>{submitting?"Estornando...":"Confirmar estorno"}</button></>}><div className="current-balance"><span>Valor recebido</span><strong>{money.format(payment.amount)}</strong></div>{!!payment.refundedAmount&&<div className="current-balance"><span>Já estornado</span><strong>{money.format(payment.refundedAmount)}</strong></div>}<div className="current-balance"><span>Disponível para estorno</span><strong>{money.format(refundable)}</strong></div><div className="form-grid"><Field l="Estorno total" wide><label className="switch-row"><input type="checkbox" checked={full} onChange={e=>{setFull(e.target.checked);if(e.target.checked)setAmount(refundable)}}/><span>Estornar o valor total disponível ({money.format(refundable)})</span></label></Field>{!full&&<Field l="Valor a estornar"><input type="number" min="0.01" max={refundable} step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field>}<Field l="Motivo do estorno" wide><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: Pedido cancelado após pagamento"/></Field></div>{effectiveAmount>refundable+0.001&&<div className="table-empty">O valor não pode ser maior que o disponível para estorno.</div>}</Modal>}
function ProgramEditor({state,onSave}:{state:RewardsState;onSave:(m:LoyaltyMode,r:number,t:number,d:string)=>void}){const[m,setM]=useState(state.program.mode),[r,setR]=useState(state.program.pointsPerReal),[t,setT]=useState(state.program.rewardThreshold),[d,setD]=useState(state.program.rewardDescription);return <div className="program-editor"><select value={m} onChange={e=>setM(e.target.value as LoyaltyMode)}><option value="points">Pontos</option><option value="buy_and_get">Compre e ganhe</option></select><input type="number" value={r} onChange={e=>setR(Number(e.target.value))}/><input type="number" value={t} onChange={e=>setT(Number(e.target.value))}/><input value={d} onChange={e=>setD(e.target.value)}/><button onClick={()=>onSave(m,r,t,d)}>Salvar</button></div>}
