import { CatalogService } from "./catalog-service.ts";
import { initialCommerceState } from "./commerce-seed.ts";
import type { CommerceState, CustomerInput, Order, OrderDraft, OrderStatus, StorageAdapter } from "./commerce-types.ts";

export const COMMERCE_STORAGE_KEY = "attual-one:commerce:v1";
const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;
const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const statuses:OrderStatus[]=["new","confirmed","preparing","ready","out_for_delivery","completed","cancelled"];

export class CommerceService {
  private readonly catalog:CatalogService;
  private readonly storage:StorageAdapter;
  constructor(storage:StorageAdapter){this.storage=storage;this.catalog=new CatalogService(storage);}
  load():CommerceState{const raw=this.storage.getItem(COMMERCE_STORAGE_KEY);if(!raw){const state=clone(initialCommerceState);this.save(state);return state;}try{return JSON.parse(raw) as CommerceState;}catch{throw new Error("Não foi possível ler clientes e pedidos.");}}
  save(state:CommerceState){this.storage.setItem(COMMERCE_STORAGE_KEY,JSON.stringify(state));}
  createCustomer(input:CustomerInput){this.validateCustomer(input);const state=this.load(),now=new Date().toISOString();state.customers.push({...input,name:input.name.trim(),phone:input.phone.trim(),id:uid("cus"),companyId:state.companyId,createdAt:now,updatedAt:now});this.save(state);return state;}
  updateCustomer(id:string,input:CustomerInput){this.validateCustomer(input);const state=this.load(),index=state.customers.findIndex(c=>c.id===id);if(index<0)throw new Error("Cliente não encontrado.");state.customers[index]={...state.customers[index],...input,name:input.name.trim(),phone:input.phone.trim(),updatedAt:new Date().toISOString()};this.save(state);return state;}
  deleteCustomer(id:string){const state=this.load();state.customers=state.customers.filter(c=>c.id!==id);state.orders=state.orders.map(o=>o.customerId===id?{...o,customerId:undefined}:o);this.save(state);return state;}
  createOrder(draft:OrderDraft){const state=this.load();const order=this.buildOrder(state,draft);state.orders.unshift(order);state.nextOrderNumber++;this.save(state);return state;}
  updateOrder(id:string,draft:OrderDraft){const state=this.load(),index=state.orders.findIndex(o=>o.id===id);if(index<0)throw new Error("Pedido não encontrado.");if(state.orders[index].status!=="new")throw new Error("Somente pedidos novos podem ser editados.");const updated=this.buildOrder(state,draft,state.orders[index]);state.orders[index]=updated;this.save(state);return state;}
  changeStatus(id:string,status:OrderStatus,cancellationReason?:string){if(!statuses.includes(status))throw new Error("Status inválido.");const state=this.load(),order=state.orders.find(o=>o.id===id);if(!order)throw new Error("Pedido não encontrado.");if(status==="cancelled"&&!cancellationReason?.trim())throw new Error("Informe o motivo do cancelamento.");if(status==="confirmed"&&!order.stockApplied){this.applyStock(order,"exit",`Pedido #${order.number} confirmado`);order.stockApplied=true;}if(status==="cancelled"&&order.stockApplied){this.applyStock(order,"entry",`Pedido #${order.number} cancelado: ${cancellationReason?.trim()}`);order.stockApplied=false;}order.status=status;if(status==="cancelled")order.cancellationReason=cancellationReason?.trim();order.updatedAt=new Date().toISOString();this.save(state);return state;}
  private applyStock(order:Order,type:"entry"|"exit",reason:string){const catalog=this.catalog.load();if(type==="exit"){for(const item of order.items){const p=catalog.products.find(x=>x.id===item.productId);if(!p||p.status==="inactive"||p.status==="out_of_stock")throw new Error(`${item.productName} está indisponível.`);if(p.trackStock&&item.quantity>p.currentStock)throw new Error(`Estoque insuficiente para ${item.productName}.`);}}for(const item of order.items){const p=this.catalog.load().products.find(x=>x.id===item.productId);if(p?.trackStock)this.catalog.moveStock(item.productId,type,item.quantity,reason);}}
  private buildOrder(state:CommerceState,draft:OrderDraft,existing?:Order):Order{if(!draft.items.length)throw new Error("Adicione pelo menos um item.");const catalog=this.catalog.load();for(const item of draft.items){const p=catalog.products.find(x=>x.id===item.productId);if(!p||p.status==="inactive"||p.status==="out_of_stock")throw new Error(`${item.productName} está indisponível.`);if(item.quantity<=0)throw new Error("A quantidade precisa ser maior que zero.");if(p.trackStock&&item.quantity>p.currentStock)throw new Error(`Estoque insuficiente para ${p.name}.`);}if(draft.fulfillment==="delivery"&&(!draft.deliveryAddress?.street.trim()||!draft.deliveryAddress.number.trim()))throw new Error("Informe o endereço de entrega.");const subtotal=draft.items.reduce((sum,item)=>sum+item.unitPrice*item.quantity,0);const total=subtotal-draft.discount+draft.deliveryFee;if(total<0)throw new Error("O total do pedido não pode ser negativo.");const customer=draft.customerId?state.customers.find(c=>c.id===draft.customerId):undefined;if(draft.customerId&&!customer)throw new Error("Cliente não encontrado.");const now=new Date().toISOString();return {...existing,id:existing?.id??uid("ord"),companyId:state.companyId,number:existing?.number??state.nextOrderNumber,customerId:customer?.id,customerName:customer?.name||draft.customerName.trim()||"Consumidor não identificado",customerPhone:customer?.phone||draft.customerPhone?.trim(),createdAt:existing?.createdAt??now,updatedAt:now,items:draft.items.map(item=>({...item,id:item.id||uid("item"),total:item.unitPrice*item.quantity})),fulfillment:draft.fulfillment,deliveryAddress:draft.fulfillment==="delivery"?draft.deliveryAddress:undefined,subtotal,discount:draft.discount,deliveryFee:draft.deliveryFee,total,paymentMethod:draft.paymentMethod,paymentStatus:draft.paymentStatus,status:existing?.status??"new",stockApplied:existing?.stockApplied??false};}
  private validateCustomer(input:CustomerInput){if(!input.name.trim())throw new Error("O nome do cliente é obrigatório.");if(!input.phone.trim())throw new Error("O telefone é obrigatório.");}
}
export const createBrowserCommerceService=()=>new CommerceService(window.localStorage);
