import { CommerceService } from "./commerce-service.ts";
import { initialRewardsState } from "./rewards-seed.ts";
import type { StorageAdapter } from "./catalog-types.ts";
import type { CouponInput,LoyaltyMode,RewardsState } from "./rewards-types.ts";
import type { PaymentMethod,PaymentStatus } from "./commerce-types.ts";
export const REWARDS_STORAGE_KEY="attual-one:rewards:v1";
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T,uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export class RewardsService{private readonly storage:StorageAdapter;private readonly commerce:CommerceService;constructor(storage:StorageAdapter){this.storage=storage;this.commerce=new CommerceService(storage)}load():RewardsState{const raw=this.storage.getItem(REWARDS_STORAGE_KEY);if(!raw){const s=clone(initialRewardsState);this.save(s);return s}try{return JSON.parse(raw) as RewardsState}catch{throw new Error("Não foi possível ler pagamentos e fidelidade.")}}save(s:RewardsState){this.storage.setItem(REWARDS_STORAGE_KEY,JSON.stringify(s))}
 createCoupon(input:CouponInput){this.validateCoupon(input);const s=this.load(),now=new Date().toISOString();if(s.coupons.some(c=>c.code===input.code.trim().toUpperCase()))throw new Error("Já existe um cupom com este código.");s.coupons.unshift({...input,code:input.code.trim().toUpperCase(),id:uid("cup"),companyId:s.companyId,usageCount:0,createdAt:now,updatedAt:now});this.save(s);return s}
 updateCoupon(id:string,input:CouponInput){this.validateCoupon(input);const s=this.load(),i=s.coupons.findIndex(c=>c.id===id);if(i<0)throw new Error("Cupom não encontrado.");s.coupons[i]={...s.coupons[i],...input,code:input.code.trim().toUpperCase(),updatedAt:new Date().toISOString()};this.save(s);return s}
 deleteCoupon(id:string){const s=this.load();s.coupons=s.coupons.filter(c=>c.id!==id);this.save(s);return s}
 calculateDiscount(code:string,subtotal:number,date=new Date()){const c=this.load().coupons.find(x=>x.code===code.trim().toUpperCase());if(!c||c.status!=="active")throw new Error("Cupom inválido ou inativo.");if(date<DateAt(c.startsAt)||date>DateEnd(c.expiresAt))throw new Error("Cupom fora da validade.");if(subtotal<c.minimumOrder)throw new Error(`Pedido mínimo de R$ ${c.minimumOrder.toFixed(2)}.`);if(c.usageLimit!==undefined&&c.usageCount>=c.usageLimit)throw new Error("Limite de uso atingido.");return Math.min(subtotal,c.type==="percentage"?subtotal*c.value/100:c.value)}
 useCoupon(code:string){const s=this.load(),c=s.coupons.find(x=>x.code===code.trim().toUpperCase());if(!c)throw new Error("Cupom não encontrado.");c.usageCount++;c.updatedAt=new Date().toISOString();this.save(s);return s}
 registerPayment(orderId:string,method:PaymentMethod,status:PaymentStatus,reference?:string,notes?:string){const commerce=this.commerce.load(),order=commerce.orders.find(o=>o.id===orderId);if(!order)throw new Error("Pedido não encontrado.");const s=this.load(),existing=s.payments.find(p=>p.orderId===orderId),now=new Date().toISOString();if(existing){existing.method=method;existing.status=status;existing.reference=reference;existing.notes=notes;existing.updatedAt=now}else{s.payments.unshift({id:uid("pay"),companyId:s.companyId,orderId,orderNumber:order.number,customerName:order.customerName,amount:order.total,method,status,reference,notes,createdAt:now,updatedAt:now})}order.paymentMethod=method;order.paymentStatus=status;order.updatedAt=now;this.commerce.save(commerce);this.save(s);return s}
 refundPayment(paymentId:string,amount:number,reason:string){if(!reason.trim())throw new Error("Informe o motivo do estorno.");if(!Number.isFinite(amount)||amount<=0)throw new Error("Informe um valor de estorno válido.");const s=this.load(),payment=s.payments.find(p=>p.id===paymentId);if(!payment)throw new Error("Pagamento não encontrado.");if(payment.status!=="paid")throw new Error("Somente pagamentos pagos podem ser estornados.");if(amount<payment.amount-0.005)throw new Error("O modo local só suporta estorno total deste pagamento.");if(amount>payment.amount+0.005)throw new Error("O valor do estorno não pode ser maior que o valor recebido.");const now=new Date().toISOString();payment.status="refunded";payment.refundedAmount=payment.amount;payment.notes=reason.trim();payment.updatedAt=now;this.save(s);const commerce=this.commerce.load(),order=commerce.orders.find(o=>o.id===payment.orderId);if(order){order.paymentStatus="refunded";order.updatedAt=now;this.commerce.save(commerce)}return s}
 syncLoyalty(){const commerce=this.commerce.load(),s=this.load(),previousIds=new Map(s.accounts.map(a=>[a.customerId,a.id]));s.accounts=[];for(const order of commerce.orders.filter(o=>o.status==="completed"&&o.customerId).sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt))){let account=s.accounts.find(a=>a.customerId===order.customerId);if(!account){account={id:previousIds.get(order.customerId!)??uid("loy"),companyId:s.companyId,customerId:order.customerId!,customerName:order.customerName,points:0,purchaseCount:0,rewardsAvailable:0,creditedOrderIds:[],updatedAt:new Date().toISOString()};s.accounts.push(account)}account.purchaseCount++;if(s.program.mode==="points"){account.points+=Math.floor(order.total*s.program.pointsPerReal);while(account.points>=s.program.rewardThreshold){account.points-=s.program.rewardThreshold;account.rewardsAvailable++}}else if(account.purchaseCount%s.program.rewardThreshold===0)account.rewardsAvailable++;account.creditedOrderIds.push(order.id);account.updatedAt=new Date().toISOString()}this.save(s);return s}
 updateProgram(mode:LoyaltyMode,pointsPerReal:number,rewardThreshold:number,rewardDescription:string){if(pointsPerReal<0||rewardThreshold<=0)throw new Error("Informe valores válidos para a fidelidade.");const s=this.load();s.program={...s.program,mode,pointsPerReal,rewardThreshold,rewardDescription:rewardDescription.trim()||"Recompensa",status:"active"};this.save(s);return s}
 private validateCoupon(i:CouponInput){if(!i.code.trim())throw new Error("Informe o código do cupom.");if(i.value<=0||i.minimumOrder<0)throw new Error("Informe valores válidos.");if(i.type==="percentage"&&i.value>100)throw new Error("O percentual não pode ultrapassar 100%.");if(Date.parse(i.expiresAt)<Date.parse(i.startsAt))throw new Error("A validade final deve ser posterior ao início.")}}
const DateAt=(value:string)=>new Date(`${value}T00:00:00`),DateEnd=(value:string)=>new Date(`${value}T23:59:59`);
export const createBrowserRewardsService=()=>new RewardsService(window.localStorage);
