import{CatalogService}from"./catalog-service.ts";import{CommerceService}from"./commerce-service.ts";import{RewardsService}from"./rewards-service.ts";import type{StorageAdapter}from"./catalog-types.ts";import type{CheckoutInput,StorefrontState}from"./storefront-types.ts";import type{Order}from"./commerce-types.ts";
export const STOREFRONT_STORAGE_KEY="attual-one:storefront:v1";const now=()=>new Date().toISOString();
const initial:StorefrontState={version:1,config:{companyId:"hamburgueria-07",name:"Hamburgueria 07",tagline:"Smash artesanal. Sabor de verdade.",logoText:"H7",coverMessage:"Seu burger favorito, do nosso balcão para você.",open:true,acceptOrdersWhenClosed:false,openingHours:"Terça a domingo · 18h às 23h",closedMessage:"Estamos fechados agora. Volte no próximo horário!",deliveryFee:6},cart:{version:1,items:[],discount:0,updatedAt:"2026-07-10T12:00:00.000Z"},submissions:{}};
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v))as T;
export class StorefrontService{private readonly storage:StorageAdapter;private readonly catalog:CatalogService;private readonly commerce:CommerceService;private readonly rewards:RewardsService;constructor(storage:StorageAdapter){this.storage=storage;this.catalog=new CatalogService(storage);this.commerce=new CommerceService(storage);this.rewards=new RewardsService(storage)}load():StorefrontState{const raw=this.storage.getItem(STOREFRONT_STORAGE_KEY);if(!raw){const s=clone(initial);this.save(s);return s}try{return JSON.parse(raw)as StorefrontState}catch{throw new Error("Não foi possível carregar a loja.")}}save(s:StorefrontState){this.storage.setItem(STOREFRONT_STORAGE_KEY,JSON.stringify(s))}
 addItem(productId:string,quantity=1,additions:string[]=[],note=""){const s=this.load(),p=this.catalog.load().products.find(x=>x.id===productId);if(!p||p.status==="inactive"||p.status==="out_of_stock")throw new Error("Produto indisponível.");if(quantity<=0)throw new Error("Quantidade inválida.");const existing=s.cart.items.find(i=>i.productId===productId&&i.additions.join("|")===additions.join("|")&&i.note===note),next=(existing?.quantity??0)+quantity;if(p.trackStock&&next>p.currentStock)throw new Error("Quantidade acima do estoque disponível.");if(existing)existing.quantity=next;else s.cart.items.push({productId,productName:p.name,unitPrice:p.promotionalPrice??p.price,quantity,additions,note});this.touch(s);return s}
 updateQuantity(index:number,quantity:number){const s=this.load(),item=s.cart.items[index];if(!item)throw new Error("Item não encontrado.");if(quantity<=0)s.cart.items.splice(index,1);else{const p=this.catalog.load().products.find(x=>x.id===item.productId);if(!p||p.status!=="available")throw new Error("Produto indisponível.");if(p.trackStock&&quantity>p.currentStock)throw new Error("Quantidade acima do estoque disponível.");item.quantity=quantity}this.touch(s);return s}
 updateItem(index:number,additions:string[],note:string){const s=this.load(),item=s.cart.items[index];if(!item)throw new Error("Item não encontrado.");item.additions=additions;item.note=note.trim();this.touch(s);return s}
 removeItem(index:number){return this.updateQuantity(index,0)}clearCart(){const s=this.load();s.cart={version:1,items:[],discount:0,updatedAt:now()};this.save(s);return s}
 applyCoupon(code:string){const s=this.load(),subtotal=this.subtotal(s);s.cart.discount=this.rewards.calculateDiscount(code,subtotal,new Date("2026-07-10T12:00:00"));s.cart.couponCode=code.trim().toUpperCase();this.touch(s);return s}
 checkout(input:CheckoutInput):{state:StorefrontState;order:Order;duplicate:boolean}{let s=this.load();const existingId=s.submissions[input.submissionId];if(existingId){const existing=this.commerce.load().orders.find(o=>o.id===existingId);if(existing)return{state:s,order:existing,duplicate:true}}if(!s.config.open&&!s.config.acceptOrdersWhenClosed)throw new Error(s.config.closedMessage);if(!s.cart.items.length)throw new Error("Seu carrinho está vazio.");if(input.identified&&(!input.name?.trim()||!input.phone?.trim()))throw new Error("Informe nome e telefone.");if(input.fulfillment==="delivery"&&(!input.address?.street.trim()||!input.address.number.trim()))throw new Error("Informe o endereço de entrega.");for(const item of s.cart.items){const p=this.catalog.load().products.find(x=>x.id===item.productId);if(!p||p.status!=="available")throw new Error(`${item.productName} está indisponível.`);if(p.trackStock&&item.quantity>p.currentStock)throw new Error(`Estoque insuficiente para ${item.productName}.`)}const subtotal=this.subtotal(s),coupon=input.couponCode?.trim()||s.cart.couponCode,discount=coupon?this.rewards.calculateDiscount(coupon,subtotal,new Date("2026-07-10T12:00:00")):0,commerce=this.commerce.createOrder({customerId:undefined,customerName:input.identified?input.name?.trim()||"":"Consumidor não identificado",customerPhone:input.identified?input.phone?.trim():undefined,items:s.cart.items.map(i=>({id:"",productId:i.productId,productName:i.productName,unitPrice:i.unitPrice,quantity:i.quantity,additions:i.additions,note:i.note,total:i.unitPrice*i.quantity})),fulfillment:input.fulfillment,deliveryAddress:input.fulfillment==="delivery"?input.address:undefined,discount,deliveryFee:input.fulfillment==="delivery"?s.config.deliveryFee:0,paymentMethod:input.paymentMethod,paymentStatus:"pending"}),order=commerce.orders[0];this.rewards.registerPayment(order.id,input.paymentMethod,"pending",undefined,"Checkout da loja pública");if(coupon)this.rewards.useCoupon(coupon);s=this.load();s.submissions[input.submissionId]=order.id;s.lastOrderId=order.id;s.cart={version:1,items:[],discount:0,updatedAt:now()};this.save(s);return{state:s,order,duplicate:false}}
 getLastOrder(){const s=this.load();return s.lastOrderId?this.commerce.load().orders.find(o=>o.id===s.lastOrderId):undefined}subtotal(s=this.load()){return s.cart.items.reduce((n,i)=>n+i.unitPrice*i.quantity,0)}private touch(s:StorefrontState){s.cart.updatedAt=now();this.save(s)}}export const createBrowserStorefrontService=()=>new StorefrontService(window.localStorage);
