import type { SupabaseClient } from "@supabase/supabase-js";
import type { LocalMigrationPreview } from "./local-to-supabase";
const cents=(value:number)=>Math.round(value*100),check=(error:{message:string}|null)=>{if(error)throw new Error(error.message)};
export async function importLocalPreview(client:SupabaseClient,companyId:string,preview:LocalMigrationPreview){
 const key=`local-v1:${preview.fingerprint}`,existing=await client.from("import_jobs").select("id,status,result").eq("company_id",companyId).eq("idempotency_key",key).maybeSingle();if(existing.data)return{duplicate:true,job:existing.data};
 const{data:job,error}=await client.from("import_jobs").insert({company_id:companyId,type:"local_storage_v1",source:"attual_one_local",status:"processing",mapping:preview.idMap,idempotency_key:key}).select().single();check(error);
 try{const c=preview.payload.catalog,q=preview.payload.commerce,r=preview.payload.rewards;
  if(c){let result=await client.from("categories").upsert(c.categories.map(x=>({id:preview.idMap[x.id],company_id:companyId,name:x.name,description:x.description,status:x.status,display_order:x.displayOrder})),{onConflict:"id"});check(result.error);result=await client.from("products").upsert(c.products.map(x=>({id:preview.idMap[x.id],company_id:companyId,category_id:preview.idMap[x.categoryId],name:x.name,description:x.description,price_cents:cents(x.price),promotional_price_cents:x.promotionalPrice==null?null:cents(x.promotionalPrice),image_url:x.imageUrl,sku:x.sku,track_stock:x.trackStock,current_stock:x.currentStock,minimum_stock:x.minimumStock,status:x.status})),{onConflict:"id"});check(result.error);if(c.movements.length){result=await client.from("stock_movements").upsert(c.movements.map(x=>({id:preview.idMap[x.id],company_id:companyId,product_id:preview.idMap[x.productId],type:x.type,quantity:x.quantity,previous_stock:x.previousStock,resulting_stock:x.resultingStock,reason:x.reason,idempotency_key:`migration:${preview.fingerprint}:${x.id}`})),{onConflict:"id"});check(result.error)}}
  if(q){let result=await client.from("customers").upsert(q.customers.map(x=>({id:preview.idMap[x.id],company_id:companyId,name:x.name,phone:x.phone,email:x.email,tax_id:x.taxId,address:x.address,notes:x.notes,status:x.status})),{onConflict:"id"});check(result.error);result=await client.from("orders").upsert(q.orders.map(x=>({id:preview.idMap[x.id],company_id:companyId,number:x.number,customer_id:x.customerId?preview.idMap[x.customerId]:null,customer_name:x.customerName,customer_phone:x.customerPhone,fulfillment:x.fulfillment,delivery_address:x.deliveryAddress,subtotal_cents:cents(x.subtotal),discount_cents:cents(x.discount),delivery_fee_cents:cents(x.deliveryFee),total_cents:cents(x.total),payment_method:x.paymentMethod,payment_status:x.paymentStatus,status:x.status,stock_applied:x.stockApplied,cancellation_reason:x.cancellationReason,source:"import",idempotency_key:`migration:${preview.fingerprint}:${x.id}`})),{onConflict:"id"});check(result.error);const items=q.orders.flatMap(o=>o.items.map(i=>({id:preview.idMap[i.id],company_id:companyId,order_id:preview.idMap[o.id],product_id:preview.idMap[i.productId],product_name:i.productName,unit_price_cents:cents(i.unitPrice),quantity:i.quantity,additions:i.additions,note:i.note,total_cents:cents(i.total)})));if(items.length){result=await client.from("order_items").upsert(items,{onConflict:"id"});check(result.error)}}
  if(r){let result=await client.from("coupons").upsert(r.coupons.map(x=>({id:preview.idMap[x.id],company_id:companyId,code:x.code,description:x.description,type:x.type,value:x.type==="fixed"?cents(x.value):x.value,minimum_order_cents:cents(x.minimumOrder),usage_limit:x.usageLimit,usage_count:x.usageCount,starts_at:x.startsAt,expires_at:x.expiresAt,status:x.status})),{onConflict:"id"});check(result.error);if(r.payments.length){result=await client.from("payments").upsert(r.payments.map(x=>({id:preview.idMap[x.id],company_id:companyId,order_id:preview.idMap[x.orderId],amount_cents:cents(x.amount),method:x.method,status:x.status,reference:x.reference,notes:x.notes,idempotency_key:`migration:${preview.fingerprint}:${x.id}`})),{onConflict:"id"});check(result.error)}result=await client.from("loyalty_rules").upsert({id:preview.idMap[r.program.id],company_id:companyId,name:r.program.name,mode:r.program.mode,points_per_real:r.program.pointsPerReal,reward_threshold:r.program.rewardThreshold,reward_description:r.program.rewardDescription,status:r.program.status},{onConflict:"id"});check(result.error);if(r.accounts.length){result=await client.from("loyalty_accounts").upsert(r.accounts.map(x=>({id:preview.idMap[x.id],company_id:companyId,customer_id:preview.idMap[x.customerId],points:x.points,purchase_count:x.purchaseCount,rewards_available:x.rewardsAvailable})),{onConflict:"id"});check(result.error)}}
  const report={counts:preview.counts,warnings:[...preview.warnings,"Histórico detalhado de fidelidade local não existe; apenas saldos consolidados foram migrados."]};check((await client.from("import_jobs").update({status:"completed",result:report}).eq("id",job.id)).error);return{duplicate:false,job:{...job,status:"completed",result:report}};
 }catch(reason){await client.from("import_jobs").update({status:"failed",result:{error:reason instanceof Error?reason.message:"Falha de importação"}}).eq("id",job.id);throw reason}
}
