begin;
set local check_function_bodies = off;
create extension if not exists pgcrypto;

create type public.company_role as enum ('owner','manager','attendant','operator');
create type public.member_status as enum ('active','inactive','invited');
create type public.order_status as enum ('new','confirmed','preparing','ready','out_for_delivery','completed','cancelled');
create type public.payment_status as enum ('pending','paid','refunded');
create type public.payment_method as enum ('pix','cash','credit_card','debit_card');
create type public.fulfillment_type as enum ('pickup','delivery','dine_in');

create table public.companies (
 id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name))>0), slug text not null unique,
 public_store_enabled boolean not null default false, public_store_open boolean not null default false, public_profile jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();
create table public.company_users (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), user_id uuid not null references auth.users(id),
 role public.company_role not null, status public.member_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id),
 unique(company_id,user_id)
);
create table public.customers (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null check(length(trim(name))>0), phone text not null,
 email text, tax_id text, address jsonb not null default '{}'::jsonb, notes text, status text not null default 'active' check(status in ('active','inactive')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), deleted_at timestamptz
);
create table public.categories (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, description text, status text not null default 'active' check(status in ('active','inactive')), display_order integer not null default 0 check(display_order>=0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), deleted_at timestamptz,
 unique(company_id,name)
);
create table public.products (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), category_id uuid not null references public.categories(id), name text not null, description text not null default '',
 price_cents integer not null check(price_cents>=0), promotional_price_cents integer check(promotional_price_cents>=0), image_url text, sku text, track_stock boolean not null default true,
 current_stock integer not null default 0 check(current_stock>=0), minimum_stock integer not null default 0 check(minimum_stock>=0), status text not null default 'available' check(status in ('available','out_of_stock','inactive')),
 is_public boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), deleted_at timestamptz,
 unique(company_id,sku), unique(id,company_id)
);
create table public.product_options (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), product_id uuid not null references public.products(id), name text not null, price_cents integer not null default 0 check(price_cents>=0), status text not null default 'active' check(status in ('active','inactive')), display_order integer not null default 0,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.stock_movements (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), product_id uuid not null references public.products(id), type text not null check(type in ('entry','exit','adjustment','reversal')),
 quantity integer not null check(quantity>=0), previous_stock integer not null check(previous_stock>=0), resulting_stock integer not null check(resulting_stock>=0), reason text not null check(length(trim(reason))>0), idempotency_key text,
 created_at timestamptz not null default now(), created_by uuid references auth.users(id), unique(company_id,idempotency_key)
);
create table public.orders (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), number bigint not null, customer_id uuid references public.customers(id), customer_name text not null default 'Consumidor não identificado', customer_phone text,
 fulfillment public.fulfillment_type not null, delivery_address jsonb, subtotal_cents integer not null check(subtotal_cents>=0), discount_cents integer not null default 0 check(discount_cents>=0), delivery_fee_cents integer not null default 0 check(delivery_fee_cents>=0), total_cents integer not null check(total_cents>=0),
 payment_method public.payment_method not null, payment_status public.payment_status not null default 'pending', status public.order_status not null default 'new', stock_applied boolean not null default false, cancellation_reason text, source text not null default 'admin' check(source in ('admin','store','import')), idempotency_key text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), deleted_at timestamptz,
 unique(company_id,number), unique(company_id,idempotency_key), check(total_cents=subtotal_cents-discount_cents+delivery_fee_cents), check(fulfillment<>'delivery' or delivery_address is not null), unique(id,company_id)
);
create table public.order_items (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid not null references public.products(id), product_name text not null, unit_price_cents integer not null check(unit_price_cents>=0), quantity integer not null check(quantity>0), additions jsonb not null default '[]'::jsonb, note text, total_cents integer not null check(total_cents>=0), created_at timestamptz not null default now(), check(total_cents=unit_price_cents*quantity)
);
create table public.payments (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_id uuid not null references public.orders(id), amount_cents integer not null check(amount_cents>=0), method public.payment_method not null, status public.payment_status not null, reference text, notes text, idempotency_key text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), unique(company_id,idempotency_key)
);
create table public.coupons (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), code text not null, description text, type text not null check(type in ('percentage','fixed')), value integer not null check(value>0), minimum_order_cents integer not null default 0 check(minimum_order_cents>=0), usage_limit integer check(usage_limit>0), usage_count integer not null default 0 check(usage_count>=0), starts_at timestamptz not null, expires_at timestamptz not null, status text not null default 'active' check(status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(company_id,code), check(expires_at>=starts_at), check(type<>'percentage' or value<=100)
);
create table public.coupon_usages (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), coupon_id uuid not null references public.coupons(id), order_id uuid not null references public.orders(id), customer_id uuid references public.customers(id), discount_cents integer not null check(discount_cents>=0), created_at timestamptz not null default now(), unique(coupon_id,order_id)
);
create table public.loyalty_rules (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, mode text not null check(mode in ('points','buy_and_get')), points_per_real numeric(10,4) not null default 1 check(points_per_real>=0), reward_threshold integer not null check(reward_threshold>0), reward_description text not null, status text not null default 'active' check(status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,name)
);
create table public.loyalty_accounts (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), customer_id uuid not null references public.customers(id), points integer not null default 0 check(points>=0), purchase_count integer not null default 0 check(purchase_count>=0), rewards_available integer not null default 0 check(rewards_available>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,customer_id)
);
create table public.loyalty_transactions (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), account_id uuid not null references public.loyalty_accounts(id), order_id uuid references public.orders(id), type text not null check(type in ('credit','debit','reward','reversal')), points integer not null default 0, purchases integer not null default 0, rewards integer not null default 0, reason text not null, idempotency_key text not null, created_at timestamptz not null default now(), created_by uuid references auth.users(id), unique(company_id,idempotency_key)
);
create table public.import_jobs (
 id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), type text not null, source text not null, status text not null check(status in ('preview','queued','processing','completed','failed')), mapping jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, idempotency_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), unique(company_id,idempotency_key)
);
create table public.audit_logs (
 id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id), user_id uuid references auth.users(id), action text not null, entity text not null, entity_id uuid, essentials jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create index customers_company_phone_idx on public.customers(company_id,phone) where deleted_at is null;
create index products_company_status_idx on public.products(company_id,status) where deleted_at is null;
create index stock_company_date_idx on public.stock_movements(company_id,created_at desc);
create index orders_company_date_idx on public.orders(company_id,created_at desc) where deleted_at is null;
create index orders_company_status_idx on public.orders(company_id,status) where deleted_at is null;
create index orders_company_number_idx on public.orders(company_id,number);
create index payments_company_status_idx on public.payments(company_id,status,created_at desc);
create index coupons_company_status_idx on public.coupons(company_id,status) where deleted_at is null;
create index audit_company_date_idx on public.audit_logs(company_id,created_at desc);

create function public.is_company_member(p_company uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from company_users where company_id=p_company and user_id=auth.uid() and status='active') $$;
create function public.has_company_role(p_company uuid,p_roles public.company_role[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from company_users where company_id=p_company and user_id=auth.uid() and status='active' and role=any(p_roles)) $$;
revoke all on function public.is_company_member(uuid) from public; grant execute on function public.is_company_member(uuid) to authenticated,anon;
revoke all on function public.has_company_role(uuid,public.company_role[]) from public; grant execute on function public.has_company_role(uuid,public.company_role[]) to authenticated;
create function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['companies','profiles','company_users','customers','categories','products','product_options','orders','payments','coupons','loyalty_rules','loyalty_accounts','import_jobs'] loop execute format('create trigger %I_touch before update on public.%I for each row execute function public.touch_updated_at()',t,t); end loop; end $$;
create function public.capture_audit() returns trigger language plpgsql security definer set search_path=public as $$ declare row_data jsonb; cid uuid; eid uuid; begin row_data=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end; cid=(row_data->>'company_id')::uuid; eid=(row_data->>'id')::uuid; insert into audit_logs(company_id,user_id,action,entity,entity_id,essentials) values(cid,auth.uid(),lower(tg_op),tg_table_name,eid,row_data-'created_by'-'updated_by'-'deleted_at'); return case when tg_op='DELETE' then old else new end; end $$;
do $$ declare t text; begin foreach t in array array['customers','categories','products','stock_movements','orders','payments','coupons','loyalty_rules','loyalty_accounts','import_jobs','company_users'] loop execute format('create trigger %I_audit after insert or update or delete on public.%I for each row execute function public.capture_audit()',t,t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['companies','profiles','company_users','customers','categories','products','product_options','stock_movements','orders','order_items','payments','coupons','coupon_usages','loyalty_rules','loyalty_accounts','loyalty_transactions','import_jobs','audit_logs'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy profiles_self on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy companies_member_read on public.companies for select to authenticated using(public.is_company_member(id));
create policy companies_owner_update on public.companies for update to authenticated using(public.has_company_role(id,array['owner']::public.company_role[])) with check(public.has_company_role(id,array['owner']::public.company_role[]));
create policy companies_public_read on public.companies for select to anon using(public_store_enabled and deleted_at is null);
create policy company_users_member_read on public.company_users for select to authenticated using(public.is_company_member(company_id));
create policy company_users_owner_write on public.company_users for all to authenticated using(public.has_company_role(company_id,array['owner']::public.company_role[])) with check(public.has_company_role(company_id,array['owner']::public.company_role[]));
do $$ declare t text; begin foreach t in array array['customers','categories','products','product_options','stock_movements','orders','order_items','payments','coupons','coupon_usages','loyalty_rules','loyalty_accounts','loyalty_transactions','import_jobs','audit_logs'] loop execute format('create policy %I_member_read on public.%I for select to authenticated using(public.is_company_member(company_id))',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['categories','products','product_options','coupons','loyalty_rules','import_jobs'] loop execute format('create policy %I_management_write on public.%I for all to authenticated using(public.has_company_role(company_id,array[''owner'',''manager'']::public.company_role[])) with check(public.has_company_role(company_id,array[''owner'',''manager'']::public.company_role[]))',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['customers','stock_movements','orders','order_items','payments','coupon_usages','loyalty_accounts','loyalty_transactions'] loop execute format('create policy %I_operations_write on public.%I for all to authenticated using(public.has_company_role(company_id,array[''owner'',''manager'',''attendant'',''operator'']::public.company_role[])) with check(public.has_company_role(company_id,array[''owner'',''manager'',''attendant'',''operator'']::public.company_role[]))',t,t); end loop; end $$;
create policy audit_insert on public.audit_logs for insert to authenticated with check(public.is_company_member(company_id) and user_id=auth.uid());
create policy categories_public_read on public.categories for select to anon using(status='active' and deleted_at is null and exists(select 1 from companies c where c.id=company_id and c.public_store_enabled));
create policy products_public_read on public.products for select to anon using(is_public and status in ('available','out_of_stock') and deleted_at is null and exists(select 1 from companies c where c.id=company_id and c.public_store_enabled));
create policy options_public_read on public.product_options for select to anon using(status='active' and deleted_at is null and exists(select 1 from companies c where c.id=company_id and c.public_store_enabled));

create function public.confirm_order(p_order uuid,p_key text) returns public.orders language plpgsql security definer set search_path=public as $$ declare o orders; i order_items; p products; begin select * into o from orders where id=p_order for update; if o.id is null or not is_company_member(o.company_id) then raise exception 'pedido não encontrado'; end if; if o.stock_applied then return o; end if; for i in select * from order_items where order_id=o.id loop select * into p from products where id=i.product_id for update; if p.status<>'available' or (p.track_stock and p.current_stock<i.quantity) then raise exception 'estoque indisponível: %',p.name; end if; if p.track_stock then update products set current_stock=current_stock-i.quantity,status=case when current_stock-i.quantity=0 then 'out_of_stock' else status end,updated_by=auth.uid() where id=p.id; insert into stock_movements(company_id,product_id,type,quantity,previous_stock,resulting_stock,reason,idempotency_key,created_by) values(o.company_id,p.id,'exit',i.quantity,p.current_stock,p.current_stock-i.quantity,'Confirmação pedido #'||o.number,p_key||':'||p.id,auth.uid()) on conflict(company_id,idempotency_key) do nothing; end if; end loop; update orders set status='confirmed',stock_applied=true,updated_by=auth.uid() where id=o.id returning * into o; return o; end $$;
create function public.cancel_order(p_order uuid,p_reason text,p_key text) returns public.orders language plpgsql security definer set search_path=public as $$ declare o orders; i order_items; p products; begin if length(trim(p_reason))=0 then raise exception 'motivo obrigatório'; end if; select * into o from orders where id=p_order for update; if o.id is null or not is_company_member(o.company_id) then raise exception 'pedido não encontrado'; end if; if o.status='cancelled' then return o; end if; if o.stock_applied then for i in select * from order_items where order_id=o.id loop select * into p from products where id=i.product_id for update; if p.track_stock then update products set current_stock=current_stock+i.quantity,status=case when status='out_of_stock' then 'available' else status end,updated_by=auth.uid() where id=p.id; insert into stock_movements(company_id,product_id,type,quantity,previous_stock,resulting_stock,reason,idempotency_key,created_by) values(o.company_id,p.id,'reversal',i.quantity,p.current_stock,p.current_stock+i.quantity,'Cancelamento pedido #'||o.number||': '||p_reason,p_key||':'||p.id,auth.uid()) on conflict(company_id,idempotency_key) do nothing; end if; end loop; end if; perform public.reverse_loyalty(o.id,p_key||':loyalty'); update orders set status='cancelled',stock_applied=false,cancellation_reason=p_reason,updated_by=auth.uid() where id=o.id returning * into o; return o; end $$;
create function public.register_payment(p_order uuid,p_method public.payment_method,p_status public.payment_status,p_reference text,p_key text) returns public.payments language plpgsql security definer set search_path=public as $$ declare o orders; result payments; begin select * into o from orders where id=p_order; if o.id is null or not is_company_member(o.company_id) then raise exception 'pedido não encontrado'; end if; insert into payments(company_id,order_id,amount_cents,method,status,reference,idempotency_key,created_by) values(o.company_id,o.id,o.total_cents,p_method,p_status,p_reference,p_key,auth.uid()) on conflict(company_id,idempotency_key) do update set method=excluded.method,status=excluded.status,reference=excluded.reference,updated_by=auth.uid() returning * into result; update orders set payment_method=p_method,payment_status=p_status,updated_by=auth.uid() where id=o.id; return result; end $$;
create function public.apply_coupon(p_order uuid,p_code text,p_key text) returns public.coupon_usages language plpgsql security definer set search_path=public as $$ declare o orders; c coupons; discount integer; result coupon_usages; begin select * into o from orders where id=p_order for update; if o.id is null or not is_company_member(o.company_id) then raise exception 'pedido não encontrado'; end if; select * into c from coupons where company_id=o.company_id and upper(code)=upper(p_code) and status='active' and now() between starts_at and expires_at for update; if c.id is null or o.subtotal_cents<c.minimum_order_cents or (c.usage_limit is not null and c.usage_count>=c.usage_limit) then raise exception 'cupom inválido'; end if; discount=least(o.subtotal_cents,case when c.type='percentage' then round(o.subtotal_cents*c.value/100.0)::integer else c.value end); insert into coupon_usages(company_id,coupon_id,order_id,customer_id,discount_cents) values(o.company_id,c.id,o.id,o.customer_id,discount) on conflict(coupon_id,order_id) do update set discount_cents=excluded.discount_cents returning * into result; if not exists(select 1 from coupon_usages where coupon_id=c.id and order_id=o.id and id<>result.id) then update coupons set usage_count=usage_count+1 where id=c.id; end if; update orders set discount_cents=discount,total_cents=subtotal_cents-discount+delivery_fee_cents,updated_by=auth.uid() where id=o.id; return result; end $$;
create function public.complete_order(p_order uuid,p_key text) returns public.orders language plpgsql security definer set search_path=public as $$ declare o orders; r loyalty_rules; a loyalty_accounts; earned integer; begin select * into o from orders where id=p_order for update; if o.id is null or not is_company_member(o.company_id) then raise exception 'pedido não encontrado'; end if; update orders set status='completed',updated_by=auth.uid() where id=o.id returning * into o; if o.customer_id is null then return o; end if; select * into r from loyalty_rules where company_id=o.company_id and status='active' order by created_at limit 1; if r.id is null then return o; end if; insert into loyalty_accounts(company_id,customer_id) values(o.company_id,o.customer_id) on conflict(company_id,customer_id) do nothing; select * into a from loyalty_accounts where company_id=o.company_id and customer_id=o.customer_id for update; if exists(select 1 from loyalty_transactions where company_id=o.company_id and idempotency_key=p_key) then return o; end if; earned=case when r.mode='points' then floor(o.total_cents/100.0*r.points_per_real)::integer else 0 end; update loyalty_accounts set points=points+earned,purchase_count=purchase_count+1,rewards_available=rewards_available+case when r.mode='buy_and_get' and (purchase_count+1)%r.reward_threshold=0 then 1 else 0 end where id=a.id; insert into loyalty_transactions(company_id,account_id,order_id,type,points,purchases,rewards,reason,idempotency_key,created_by) values(o.company_id,a.id,o.id,'credit',earned,1,case when r.mode='buy_and_get' and (a.purchase_count+1)%r.reward_threshold=0 then 1 else 0 end,'Conclusão pedido #'||o.number,p_key,auth.uid()); return o; end $$;
create function public.reverse_loyalty(p_order uuid,p_key text) returns void language plpgsql security definer set search_path=public as $$ declare tx loyalty_transactions; begin if exists(select 1 from loyalty_transactions where idempotency_key=p_key) then return; end if; select * into tx from loyalty_transactions where order_id=p_order and type='credit' order by created_at desc limit 1; if tx.id is null then return; end if; update loyalty_accounts set points=greatest(0,points-tx.points),purchase_count=greatest(0,purchase_count-tx.purchases),rewards_available=greatest(0,rewards_available-tx.rewards) where id=tx.account_id; insert into loyalty_transactions(company_id,account_id,order_id,type,points,purchases,rewards,reason,idempotency_key,created_by) values(tx.company_id,tx.account_id,p_order,'reversal',-tx.points,-tx.purchases,-tx.rewards,'Estorno por cancelamento',p_key,auth.uid()); end $$;
grant execute on function public.confirm_order(uuid,text),public.cancel_order(uuid,text,text),public.register_payment(uuid,public.payment_method,public.payment_status,text,text),public.apply_coupon(uuid,text,text),public.complete_order(uuid,text),public.reverse_loyalty(uuid,text) to authenticated;
commit;
