-- Organograma institucional do Grupo Lira de Comunicação
-- Estrutura oficial aprovada em 29/09/2026.

create table if not exists public.institutional_nodes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null check (length(trim(name)) > 0),
  node_type text not null check (node_type in ('group','pillar','brand','project','platform','system')),
  parent_id uuid null references public.institutional_nodes(id) on delete restrict,
  status text not null default 'active' check (status in ('active','planned','paused','archived')),
  display_order integer not null default 0 check (display_order >= 0),
  is_official boolean not null default true,
  description text null,
  responsible text null,
  website text null,
  instagram text null,
  created_by uuid null references auth.users(id),
  updated_by uuid null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint institutional_nodes_not_self_parent check (parent_id is null or parent_id <> id)
);

create index if not exists institutional_nodes_parent_order_idx on public.institutional_nodes(parent_id, display_order, name);

alter table public.institutional_nodes enable row level security;
grant select, insert, update, delete on table public.institutional_nodes to authenticated;
revoke all on table public.institutional_nodes from anon;

drop policy if exists "institutional_nodes_select_authenticated" on public.institutional_nodes;
create policy "institutional_nodes_select_authenticated" on public.institutional_nodes for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists "institutional_nodes_insert_authenticated" on public.institutional_nodes;
create policy "institutional_nodes_insert_authenticated" on public.institutional_nodes for insert to authenticated with check ((select auth.uid()) is not null);
drop policy if exists "institutional_nodes_update_authenticated" on public.institutional_nodes;
create policy "institutional_nodes_update_authenticated" on public.institutional_nodes for update to authenticated using ((select auth.uid()) is not null) with check ((select auth.uid()) is not null);
drop policy if exists "institutional_nodes_delete_authenticated" on public.institutional_nodes;
create policy "institutional_nodes_delete_authenticated" on public.institutional_nodes for delete to authenticated using ((select auth.uid()) is not null);

create table if not exists public.institutional_change_log (
  id bigint generated by default as identity primary key,
  node_id uuid null,
  action text not null check (action in ('insert','update','delete')),
  before_data jsonb null,
  after_data jsonb null,
  actor_id uuid null references auth.users(id),
  occurred_at timestamptz not null default now()
);
create index if not exists institutional_change_log_occurred_idx on public.institutional_change_log(occurred_at desc);
alter table public.institutional_change_log enable row level security;
grant select, insert on table public.institutional_change_log to authenticated;
revoke update, delete on table public.institutional_change_log from authenticated;
revoke all on table public.institutional_change_log from anon;
drop policy if exists "institutional_change_log_select_authenticated" on public.institutional_change_log;
create policy "institutional_change_log_select_authenticated" on public.institutional_change_log for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists "institutional_change_log_insert_authenticated" on public.institutional_change_log;
create policy "institutional_change_log_insert_authenticated" on public.institutional_change_log for insert to authenticated with check ((select auth.uid()) is not null and (actor_id is null or actor_id = (select auth.uid())));

create table if not exists public.institutional_versions (
  id uuid primary key default gen_random_uuid(),
  version_label text not null unique,
  note text null,
  snapshot jsonb not null,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.institutional_versions enable row level security;
grant select, insert on table public.institutional_versions to authenticated;
revoke update, delete on table public.institutional_versions from authenticated;
revoke all on table public.institutional_versions from anon;
drop policy if exists "institutional_versions_select_authenticated" on public.institutional_versions;
create policy "institutional_versions_select_authenticated" on public.institutional_versions for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists "institutional_versions_insert_authenticated" on public.institutional_versions;
create policy "institutional_versions_insert_authenticated" on public.institutional_versions for insert to authenticated with check ((select auth.uid()) is not null and (created_by is null or created_by = (select auth.uid())));

create or replace function public.institutional_nodes_set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  if tg_op = 'INSERT' and new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end;
$$;

drop trigger if exists institutional_nodes_set_updated_at_trigger on public.institutional_nodes;
create trigger institutional_nodes_set_updated_at_trigger before insert or update on public.institutional_nodes for each row execute function public.institutional_nodes_set_updated_at();

create or replace function public.institutional_nodes_audit()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.institutional_change_log(node_id, action, before_data, after_data, actor_id) values (new.id, 'insert', null, to_jsonb(new), auth.uid());
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.institutional_change_log(node_id, action, before_data, after_data, actor_id) values (new.id, 'update', to_jsonb(old), to_jsonb(new), auth.uid());
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.institutional_change_log(node_id, action, before_data, after_data, actor_id) values (old.id, 'delete', to_jsonb(old), null, auth.uid());
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists institutional_nodes_audit_trigger on public.institutional_nodes;
create trigger institutional_nodes_audit_trigger after insert or update or delete on public.institutional_nodes for each row execute function public.institutional_nodes_audit();

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
values ('grupo-lira','GRUPO LIRA DE COMUNICAÇÃO','group',null,0,'active',true)
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select v.code,v.name,'pillar',r.id,v.ord,'active',true
from (values ('midia','MÍDIA',10),('comunicacao-producao','COMUNICAÇÃO E PRODUÇÃO',20),('cultura-eventos-projetos','CULTURA, EVENTOS E PROJETOS',30),('tecnologia-inovacao','TECNOLOGIA E INOVAÇÃO',40)) as v(code,name,ord)
cross join (select id from public.institutional_nodes where code='grupo-lira') r
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select v.code,v.name,'brand',p.id,v.ord,'active',true
from (values ('tv-attual','TV Attual',10),('radio-attual','Rádio Attual',20)) as v(code,name,ord)
cross join (select id from public.institutional_nodes where code='midia') p
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select v.code,v.name,'brand',p.id,v.ord,'active',true
from (values ('att-comunica','ATT Comunica',10),('studio-lira','Studio Lira',20),('attual-records','Attual Records',30)) as v(code,name,ord)
cross join (select id from public.institutional_nodes where code='comunicacao-producao') p
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select v.code,v.name,'project',p.id,v.ord,'active',true
from (values ('femac-sp','FEMAC-SP',10),('miss-cacapava','Miss Caçapava',20),('taiada-fashion','Taiada Fashion',30)) as v(code,name,ord)
cross join (select id from public.institutional_nodes where code='cultura-eventos-projetos') p
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select 'lira-technology','Lira Technology','brand',p.id,10,'active',true from public.institutional_nodes p where p.code='tecnologia-inovacao'
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;

insert into public.institutional_nodes (code,name,node_type,parent_id,display_order,status,is_official)
select v.code,v.name,'platform',p.id,v.ord,'active',true
from (values ('attual-one','ATTUAL ONE',10),('attual-autopilot','ATTUAL AUTOPILOT',20),('attual-display-indoor','ATTUAL DISPLAY / INDOOR',30),('attual-conecta-imoveis','ATTUAL CONECTA IMÓVEIS',40),('casting-360','CASTING 360',50),('tv-attual-app','TV ATTUAL APP',60),('attual-conecta-social','ATTUAL CONECTA SOCIAL',70)) as v(code,name,ord)
cross join (select id from public.institutional_nodes where code='lira-technology') p
on conflict (code) do update set name=excluded.name,node_type=excluded.node_type,parent_id=excluded.parent_id,display_order=excluded.display_order,status=excluded.status,is_official=excluded.is_official;
